#pragma once
// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from web/Shared/CuarkDefs.ts by running 'crow-idl
// ...'. If you need to change this file, edit web/Shared/CuarkDefs.ts and run
// the crow-idl command again. Or, if you need to change the generation process,
// put up a pull-request to https://github.com/kevinfrei/ts-cpp-tooling
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by cassette v0.1.0

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <iomanip>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <crow/json.h>

// TODO: Configure this header to be an external blob

/****
Conversion to JSON stuff
****/

// Helper stuff I need
// bool value for an enum-class to enable JSON specialization
template <typename T>
struct is_enum_class {
  static constexpr bool value =
      std::is_enum_v<T> && !std::is_convertible_v<T, int>;
};

template <typename T>
inline constexpr bool is_enum_class_v = is_enum_class<T>::value;

template <typename T>
constexpr auto underlying_cast(T e) noexcept {
  static_assert(std::is_enum_v<T>,
                "underlying_cast can only be used with enum types.");
  return static_cast<std::underlying_type_t<T>>(e);
}

/****
Conversion to JSON stuff
****/

// By default, simple stuff can be converted to json
// The enable_if_t is to prevent this version from being used by enum classes,
// which get extra validation to prevent stupidity from accidentally leaking.
template <typename T, typename Enabled = void>
struct impl_to_json {
  static inline crow::json::wvalue process(const T& value) {
    return crow::json::wvalue(value);
  }
};

template <typename T>
inline std::enable_if_t<!is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T& value) {
  return impl_to_json<T>::process(value);
}

template <typename T>
inline std::enable_if_t<is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T value) {
  return crow::json::wvalue(static_cast<std::underlying_type_t<T>>(value));
}

template <>
struct impl_to_json<uint64_t> {
  static inline crow::json::wvalue process(const uint64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

template <>
struct impl_to_json<int64_t> {
  static inline crow::json::wvalue process(const int64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

// A little extra work for string_view's:
template <>
struct impl_to_json<std::string_view> {
  static inline crow::json::wvalue process(std::string_view value) {
    return crow::json::wvalue(std::string{value});
  }
};

// Vector<T> specialization
template <typename T>
struct impl_to_json<std::vector<T>> {
  static inline crow::json::wvalue process(const std::vector<T>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    for (uint32_t i = 0; i < value.size(); i++) {
      vec[i] = to_json(value[i]);
    }
    return vec;
  }
};

// Handle char's specifically. Hurray dumb Javascript?
template <>
struct impl_to_json<char> {
  static inline crow::json::wvalue process(char value) {
    return crow::json::wvalue(std::string(1, value));
  }
};

template <typename... Args>
struct impl_to_json<std::tuple<Args...>> {
  using tup_type = std::tuple<Args...>;
  // Tuples in JSON are "just" arrays with the right size & types.
  // Doing that is...complicated.
  template <size_t Index, typename T>
  static inline void element_helper(const tup_type& tuple,
                                    crow::json::wvalue& container) {
    container[Index] = to_json(std::get<Index>(tuple));
  }
  // This is a compile time 'call the helper for each type' thing.
  template <size_t... Is>
  static inline void recurse_helper(const tup_type& tuple,
                                    crow::json::wvalue& json_list,
                                    std::index_sequence<Is...>) {
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(tuple, json_list)),
     ...);
  }
  // make_index_sequence is the magic to do something different per tuple-item
  static inline crow::json::wvalue process(const std::tuple<Args...>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    recurse_helper(value, vec, std::make_index_sequence<sizeof...(Args)>{});
    return vec;
  }
};

// I didn't need this for Windows, but I do for Linux/Mac because the map
// elem type is std::tuple on one, but a std::pair on the other
template <typename Iter>
inline crow::json::wvalue impl_vec_pair_to_json(const Iter& begin,
                                                const Iter& end) {
  std::vector<crow::json::wvalue> vec;
  for (auto it = begin; it != end; ++it) {
    crow::json::wvalue pair{std::vector<crow::json::wvalue>()};
    auto& [first, second] = *it;
    pair[0] = to_json(first);
    pair[1] = to_json(second);
    vec.push_back(pair);
  }
  return vec;
}

// My pickling framework sends JS Maps as this:
// {"@dataType":"freik.Map","@dataValue":[["a",1],["c",2],["b",3]]}
template <typename K, typename V>
struct impl_to_json<std::map<K, V>> {
  static inline crow::json::wvalue process(const std::map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

template <typename K, typename V>
struct impl_to_json<std::unordered_map<K, V>> {
  static inline crow::json::wvalue process(
      const std::unordered_map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

// My pickling framework sends JS Sets as this:
// {"@dataType":"freik.Set","@dataValue":["a", "c", "b"]}
template <typename T>
struct impl_to_json<std::unordered_set<T>> {
  static inline crow::json::wvalue process(const std::unordered_set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::set<T>> {
  static inline crow::json::wvalue process(const std::set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::optional<T>> {
  static inline crow::json::wvalue process(const std::optional<T>& value) {
    if (value.has_value()) {
      return to_json(*value);
    } else {
      return crow::json::wvalue(nullptr);
    }
  }
};

/****
Conversion from JSON stuff
****/

// By default, we can't read a random value from a json value
// (i.e. everything must be specialized) and it's easier to
// do this with a partial specialization of a struct :/
template <typename T, typename Enabled = void>
struct impl_from_json {
  static inline std::optional<T> process(const crow::json::rvalue&) {
    return std::nullopt;
  }
};

// Anything that doesn't either fully specialize this function,
// or partially (or fully...) specialize the above struct gets std::nullopt.
template <typename T>
inline std::optional<T> from_json(const crow::json::rvalue& json) {
  return impl_from_json<T>::process(json);
}

// Chars are a little weird, cuz, Javascript
template <>
inline std::optional<char> from_json<char>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = json.s();
  if (str.size() != 1) {
    return std::nullopt;
  }
  return static_cast<char>(str[0]);
}

template <>
inline std::optional<uint8_t> from_json<uint8_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint8_t>(json.u());
}

template <>
inline std::optional<int8_t> from_json<int8_t>(const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int8_t>(json.u());
}

template <>
inline std::optional<uint16_t> from_json<uint16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint16_t>(json.u());
}

template <>
inline std::optional<int16_t> from_json<int16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int16_t>(json.u());
}

template <>
inline std::optional<uint32_t> from_json<uint32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint32_t>(json.u());
}

template <>
inline std::optional<int32_t> from_json<int32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int32_t>(json.u());
}

template <>
inline std::optional<uint64_t> from_json<uint64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoull(str);
}

template <>
inline std::optional<int64_t> from_json<int64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoll(str);
}

template <>
inline std::optional<float> from_json<float>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<float>(json.d());
}

template <>
inline std::optional<double> from_json<double>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<double>(json.d());
}

template <>
inline std::optional<bool> from_json<bool>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::True &&
      json.t() != crow::json::type::False) {
    return std::nullopt;
  }
  return json.t() == crow::json::type::True;
}

template <>
inline std::optional<std::string> from_json<std::string>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  return std::string(json.s());
}

// std::vector specialization:
template <typename T>
struct impl_from_json<std::vector<T>> {
  using value_type = T;
  static inline std::optional<std::vector<value_type>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    std::vector<value_type> vec;
    vec.reserve(json.size());
    for (size_t i = 0; i < json.size(); i++) {
      auto item = from_json<value_type>(json[i]);
      if (!item) {
        return std::nullopt;
      }
      vec.push_back(*item);
    }
    return vec;
  }
};

// std::tuple specialization:
// TODO: Explain this, as it is rather messsy.
template <typename... Args>
struct impl_from_json<std::tuple<Args...>> {
 private:
  using tup_type = std::tuple<Args...>;
  template <size_t Index, typename T>
  static inline std::optional<T> element_helper(
      tup_type& tuple, bool& failed, const crow::json::rvalue& container) {
    std::optional<T> res = from_json<T>(container[Index]);
    failed = failed || !res.has_value();
    if (res.has_value()) {
      std::get<Index>(tuple) = res.value();
    }
    return res;
  }

  template <size_t... Is>
  static inline std::optional<tup_type> recurse(
      const crow::json::rvalue& container, std::index_sequence<Is...>) {
    tup_type res;
    bool failed = false;
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(
         res, failed, container)),
     ...);
    if (failed)
      return std::nullopt;
    return res;
  }

 public:
  static inline std::optional<tup_type> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    // Check exact tuple size
    if (json.size() != sizeof...(Args)) {
      return std::nullopt;
    }
    tup_type t;
    return recurse(json, std::make_index_sequence<sizeof...(Args)>{});
  }
};

// std::set/unordered_set specialization common code:
template <template <typename...> class SetType, typename Elem>
struct impl_set_helper_from_json {
  static inline std::optional<SetType<Elem>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Set") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    SetType<Elem> m;
    for (const auto& item : dataValue) {
      auto value = from_json<Elem>(item);
      if (!value) {
        return std::nullopt;
      }
      m.insert(*value);
    }
    return m;
  }
};

// std::set specialization
template <typename Elem>
struct impl_from_json<std::set<Elem>> {
  static inline std::optional<std::set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::set, Elem>::process(json);
  }
};

// std::unordered_set specialization
template <typename Elem>
struct impl_from_json<std::unordered_set<Elem>> {
  static inline std::optional<std::unordered_set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::unordered_set, Elem>::process(json);
  }
};

// std::map/unordered specialization helper:
template <template <typename...> class MapType, typename K, typename V>
struct impl_map_helper_from_json {
  static inline std::optional<MapType<K, V>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Map") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    MapType<K, V> m;
    for (const auto& item : dataValue) {
      if (item.t() != crow::json::type::List || item.size() != 2) {
        return std::nullopt;
      }
      auto key = from_json<K>(item[0]);
      auto value = from_json<V>(item[1]);
      if (!key || !value) {
        return std::nullopt;
      }
      m[*key] = *value;
    }
    return m;
  }
};

// std::map specialization
template <typename K, typename V>
struct impl_from_json<std::map<K, V>> {
  static inline std::optional<std::map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::map, K, V>::process(json);
  }
};

// std::unordered_set specialization
template <typename K, typename V>
struct impl_from_json<std::unordered_map<K, V>> {
  static inline std::optional<std::unordered_map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::unordered_map, K, V>::process(json);
  }
};

// Enum's, specifically for my gen'ed enum types, which include an
// 'is_valid' free function overload
template <typename T>
struct impl_from_json<T, std::enable_if_t<is_enum_class_v<T>>> {
  static inline std::optional<T> process(const crow::json::rvalue& json) {
    using IntType = std::underlying_type_t<T>;
    std::optional<IntType> underlyingValue = from_json<IntType>(json);
    if (!underlyingValue.has_value())
      return std::nullopt;
    T val = static_cast<T>(underlyingValue.value());
    // Check that the enumeration is actually defined
    if (is_valid(val))
      return val;
    return std::nullopt;
  }
};

/* Horsing around a little bit
template <typename T>
struct impl_from_json<std::optional<T>> {
  static inline std::optional<std::optional<T>> process(
      const crow::json::rvalue& json) {
    if (json.t() == crow::json::type::Null) {
      return std::nullopt;
    }
    auto val = from_json<T>(json);
    if (!val.has_value()) {
      return std::nullopt;
    }
    return val;
  }
};
*/

// TODO: End Configure this header to be an external blob

namespace Shared {

template <typename T>
constexpr std::optional<T> from_string(std::string_view str);

#pragma region string enum Keys

enum class Keys {
  Find,
  Settings,
  Next,
  Prev,
  Tools,
  AddFileLocation,
  Albums,
  Artists,
  Backward10s,
  Forward10s,
  NextTrack,
  NowPlaying,
  Play,
  Playlists,
  PreviousTrack,
  Repeat,
  SavePlaylist,
  Shuffle,
  Songs,
  ToggleMiniPlayer
};

inline constexpr bool is_valid(Keys _value) {
  switch (_value) {
    case Keys::Find:
    case Keys::Settings:
    case Keys::Next:
    case Keys::Prev:
    case Keys::Tools:
    case Keys::AddFileLocation:
    case Keys::Albums:
    case Keys::Artists:
    case Keys::Backward10s:
    case Keys::Forward10s:
    case Keys::NextTrack:
    case Keys::NowPlaying:
    case Keys::Play:
    case Keys::Playlists:
    case Keys::PreviousTrack:
    case Keys::Repeat:
    case Keys::SavePlaylist:
    case Keys::Shuffle:
    case Keys::Songs:
    case Keys::ToggleMiniPlayer:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(Keys _value) {
  switch (_value) {
    case Keys::Find:
      return "F";
    case Keys::Settings:
      return ",";
    case Keys::Next:
      return "Right";
    case Keys::Prev:
      return "Left";
    case Keys::Tools:
      return "L";
    case Keys::AddFileLocation:
      return "O";
    case Keys::Albums:
      return "2";
    case Keys::Artists:
      return "3";
    case Keys::Backward10s:
      return "[";
    case Keys::Forward10s:
      return "]";
    case Keys::NextTrack:
      return "Right";
    case Keys::NowPlaying:
      return "1";
    case Keys::Play:
      return "P";
    case Keys::Playlists:
      return "5";
    case Keys::PreviousTrack:
      return "Left";
    case Keys::Repeat:
      return "T";
    case Keys::SavePlaylist:
      return "S";
    case Keys::Shuffle:
      return "R";
    case Keys::Songs:
      return "4";
    case Keys::ToggleMiniPlayer:
      return "9";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<Keys> from_string<Keys>(std::string_view str) {
  if (str == "F")
    return Keys::Find;
  if (str == ",")
    return Keys::Settings;
  if (str == "Right")
    return Keys::Next;
  if (str == "Left")
    return Keys::Prev;
  if (str == "L")
    return Keys::Tools;
  if (str == "O")
    return Keys::AddFileLocation;
  if (str == "2")
    return Keys::Albums;
  if (str == "3")
    return Keys::Artists;
  if (str == "[")
    return Keys::Backward10s;
  if (str == "]")
    return Keys::Forward10s;
  if (str == "Right")
    return Keys::NextTrack;
  if (str == "1")
    return Keys::NowPlaying;
  if (str == "P")
    return Keys::Play;
  if (str == "5")
    return Keys::Playlists;
  if (str == "Left")
    return Keys::PreviousTrack;
  if (str == "T")
    return Keys::Repeat;
  if (str == "S")
    return Keys::SavePlaylist;
  if (str == "R")
    return Keys::Shuffle;
  if (str == "4")
    return Keys::Songs;
  if (str == "9")
    return Keys::ToggleMiniPlayer;
  return std::nullopt;
}

#pragma endregion string enum Keys

#pragma region string enum StrId

enum class StrId {
  FilePath,
  FilesSelected,
  ErrNotSingleAndNotMultiple,
  ErrSingleAndMultiple,
  ViewSettings,
  ViewTools,
  Mono,
  Stereo,
  Quadrophonic,
  Channels,
  BitDepth,
  Duration,
  MDHeaderField,
  MDHeaderValue,
  RawMetadata,
  ChooseCoverArt,
  ImageName,
  Title,
  ArtistTooltip,
  Artists,
  Album,
  Year,
  TrackNum,
  DiskNum,
  DiskName,
  Compilation,
  Soundtrack,
  AdditionalArtists,
  VariationsTooltip,
  Variations,
  AlbumCover,
  ChooseFile,
  FromClipboard,
  ViewNowPlaying,
  ViewAlbums,
  ViewArtists,
  ViewSongs,
  ViewPlaylists,
  ImportFiles
};

inline constexpr bool is_valid(StrId _value) {
  switch (_value) {
    case StrId::FilePath:
    case StrId::FilesSelected:
    case StrId::ErrNotSingleAndNotMultiple:
    case StrId::ErrSingleAndMultiple:
    case StrId::ViewSettings:
    case StrId::ViewTools:
    case StrId::Mono:
    case StrId::Stereo:
    case StrId::Quadrophonic:
    case StrId::Channels:
    case StrId::BitDepth:
    case StrId::Duration:
    case StrId::MDHeaderField:
    case StrId::MDHeaderValue:
    case StrId::RawMetadata:
    case StrId::ChooseCoverArt:
    case StrId::ImageName:
    case StrId::Title:
    case StrId::ArtistTooltip:
    case StrId::Artists:
    case StrId::Album:
    case StrId::Year:
    case StrId::TrackNum:
    case StrId::DiskNum:
    case StrId::DiskName:
    case StrId::Compilation:
    case StrId::Soundtrack:
    case StrId::AdditionalArtists:
    case StrId::VariationsTooltip:
    case StrId::Variations:
    case StrId::AlbumCover:
    case StrId::ChooseFile:
    case StrId::FromClipboard:
    case StrId::ViewNowPlaying:
    case StrId::ViewAlbums:
    case StrId::ViewArtists:
    case StrId::ViewSongs:
    case StrId::ViewPlaylists:
    case StrId::ImportFiles:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StrId _value) {
  switch (_value) {
    case StrId::FilePath:
      return "File Path";
    case StrId::FilesSelected:
      return "Files Selected";
    case StrId::ErrNotSingleAndNotMultiple:
      return "Not Single and not Multiple (This is a bug!)";
    case StrId::ErrSingleAndMultiple:
      return "Both Single and Multiple (This is a bug!)";
    case StrId::ViewSettings:
      return "Settings";
    case StrId::ViewTools:
      return "Tools";
    case StrId::Mono:
      return "mono";
    case StrId::Stereo:
      return "stereo";
    case StrId::Quadrophonic:
      return "quadrophonic";
    case StrId::Channels:
      return " channels";
    case StrId::BitDepth:
      return "bit";
    case StrId::Duration:
      return "Duration:";
    case StrId::MDHeaderField:
      return "Field";
    case StrId::MDHeaderValue:
      return "Value";
    case StrId::RawMetadata:
      return "Raw Metadata";
    case StrId::ChooseCoverArt:
      return "Select Cover Art Image";
    case StrId::ImageName:
      return "Images";
    case StrId::Title:
      return "Title";
    case StrId::ArtistTooltip:
      return "Multiple artists are specified like this: 'Artist 1, Artist 2 & "
             "Artist 3'";
    case StrId::Artists:
      return "Artist(s)";
    case StrId::Album:
      return "Album";
    case StrId::Year:
      return "Year";
    case StrId::TrackNum:
      return "Track #";
    case StrId::DiskNum:
      return "Disk #";
    case StrId::DiskName:
      return "Disk Name";
    case StrId::Compilation:
      return "Compilation";
    case StrId::Soundtrack:
      return "Soundtrack";
    case StrId::AdditionalArtists:
      return "Additional Artist(s)";
    case StrId::VariationsTooltip:
      return "Separate vartiations with a semicolon";
    case StrId::Variations:
      return "Variation(s)";
    case StrId::AlbumCover:
      return "Album Cover";
    case StrId::ChooseFile:
      return "Choose File...";
    case StrId::FromClipboard:
      return "From Clipboard";
    case StrId::ViewNowPlaying:
      return "Now Playing";
    case StrId::ViewAlbums:
      return "Albums";
    case StrId::ViewArtists:
      return "Artists";
    case StrId::ViewSongs:
      return "All Songs";
    case StrId::ViewPlaylists:
      return "Playlists";
    case StrId::ImportFiles:
      return "Import Files...";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StrId> from_string<StrId>(std::string_view str) {
  if (str == "File Path")
    return StrId::FilePath;
  if (str == "Files Selected")
    return StrId::FilesSelected;
  if (str == "Not Single and not Multiple (This is a bug!)")
    return StrId::ErrNotSingleAndNotMultiple;
  if (str == "Both Single and Multiple (This is a bug!)")
    return StrId::ErrSingleAndMultiple;
  if (str == "Settings")
    return StrId::ViewSettings;
  if (str == "Tools")
    return StrId::ViewTools;
  if (str == "mono")
    return StrId::Mono;
  if (str == "stereo")
    return StrId::Stereo;
  if (str == "quadrophonic")
    return StrId::Quadrophonic;
  if (str == " channels")
    return StrId::Channels;
  if (str == "bit")
    return StrId::BitDepth;
  if (str == "Duration:")
    return StrId::Duration;
  if (str == "Field")
    return StrId::MDHeaderField;
  if (str == "Value")
    return StrId::MDHeaderValue;
  if (str == "Raw Metadata")
    return StrId::RawMetadata;
  if (str == "Select Cover Art Image")
    return StrId::ChooseCoverArt;
  if (str == "Images")
    return StrId::ImageName;
  if (str == "Title")
    return StrId::Title;
  if (str ==
      "Multiple artists are specified like this: 'Artist 1, Artist 2 & Artist "
      "3'")
    return StrId::ArtistTooltip;
  if (str == "Artist(s)")
    return StrId::Artists;
  if (str == "Album")
    return StrId::Album;
  if (str == "Year")
    return StrId::Year;
  if (str == "Track #")
    return StrId::TrackNum;
  if (str == "Disk #")
    return StrId::DiskNum;
  if (str == "Disk Name")
    return StrId::DiskName;
  if (str == "Compilation")
    return StrId::Compilation;
  if (str == "Soundtrack")
    return StrId::Soundtrack;
  if (str == "Additional Artist(s)")
    return StrId::AdditionalArtists;
  if (str == "Separate vartiations with a semicolon")
    return StrId::VariationsTooltip;
  if (str == "Variation(s)")
    return StrId::Variations;
  if (str == "Album Cover")
    return StrId::AlbumCover;
  if (str == "Choose File...")
    return StrId::ChooseFile;
  if (str == "From Clipboard")
    return StrId::FromClipboard;
  if (str == "Now Playing")
    return StrId::ViewNowPlaying;
  if (str == "Albums")
    return StrId::ViewAlbums;
  if (str == "Artists")
    return StrId::ViewArtists;
  if (str == "All Songs")
    return StrId::ViewSongs;
  if (str == "Playlists")
    return StrId::ViewPlaylists;
  if (str == "Import Files...")
    return StrId::ImportFiles;
  return std::nullopt;
}

#pragma endregion string enum StrId

#pragma region linear enum CurrentView
enum class CurrentView {
  disabled = -1,
  none = 0,
  settings = 1,
  tools = 2,
  search = 3,
  recent = 101,
  albums = 102,
  artists = 103,
  songs = 104,
  playlists = 105,
  now_playing = 106,
};

inline constexpr bool is_valid(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
    case CurrentView::none:
    case CurrentView::settings:
    case CurrentView::tools:
    case CurrentView::search:
    case CurrentView::recent:
    case CurrentView::albums:
    case CurrentView::artists:
    case CurrentView::songs:
    case CurrentView::playlists:
    case CurrentView::now_playing:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
      return "disabled";
    case CurrentView::none:
      return "none";
    case CurrentView::settings:
      return "settings";
    case CurrentView::tools:
      return "tools";
    case CurrentView::search:
      return "search";
    case CurrentView::recent:
      return "recent";
    case CurrentView::albums:
      return "albums";
    case CurrentView::artists:
      return "artists";
    case CurrentView::songs:
      return "songs";
    case CurrentView::playlists:
      return "playlists";
    case CurrentView::now_playing:
      return "now_playing";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
      return "-1";
    case CurrentView::none:
      return "0";
    case CurrentView::settings:
      return "1";
    case CurrentView::tools:
      return "2";
    case CurrentView::search:
      return "3";
    case CurrentView::recent:
      return "101";
    case CurrentView::albums:
      return "102";
    case CurrentView::artists:
      return "103";
    case CurrentView::songs:
      return "104";
    case CurrentView::playlists:
      return "105";
    case CurrentView::now_playing:
      return "106";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<CurrentView> from_string<CurrentView>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  CurrentView _res = static_cast<CurrentView>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum CurrentView

#pragma region linear enum IpcCall
enum class IpcCall : std::uint16_t {
  Unknown = 0,
  ReadFromStorage = 1,
  WriteToStorage = 2,
  DeleteFromStorage = 3,
  MinimizeWindow = 4,
  MaximizeWindow = 5,
  RestoreWindow = 6,
  CloseWindow = 7,
  IsDev = 8,
  AsyncData = 9,
  MenuAction = 10,
  ShowOpenDialog = 11,
  GetFileSystemRoots = 12,
  GetNamedLocations = 13,
  GetFolderContents = 14,
  GetPlaylists = 1001,
  LoadPlaylist = 1002,
  RenamePlaylist = 1003,
  SavePlaylist = 1004,
  DeletePlaylist = 1005,
  SetPlaylists = 1006,
  ClearHates = 1007,
  ClearLikes = 1008,
  ClearLocalOverrides = 1009,
  FlushImageCache = 1010,
  FlushMetadataCache = 1011,
  GetHates = 1012,
  GetLikes = 1013,
  GetMediaInfo = 1014,
  GetMusicDatabase = 1015,
  Search = 1016,
  SetHates = 1017,
  SetLikes = 1018,
  SetMediaInfo = 1019,
  SetSaveMenu = 1020,
  ShowFile = 1021,
  ShowLocFromKey = 1022,
  ShowMenu = 1023,
  SubstrSearch = 1024,
  TranscodingBegin = 1025,
  UploadImage = 1026,
  GetPicUri = 1027,
  GetIgnoreList = 1028,
  AddIgnoreItem = 1029,
  RemoveIgnoreItem = 1030,
  PushIgnoreList = 1031,
  IgnoreListId = 1032,
};

inline constexpr bool is_valid(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
    case IpcCall::ReadFromStorage:
    case IpcCall::WriteToStorage:
    case IpcCall::DeleteFromStorage:
    case IpcCall::MinimizeWindow:
    case IpcCall::MaximizeWindow:
    case IpcCall::RestoreWindow:
    case IpcCall::CloseWindow:
    case IpcCall::IsDev:
    case IpcCall::AsyncData:
    case IpcCall::MenuAction:
    case IpcCall::ShowOpenDialog:
    case IpcCall::GetFileSystemRoots:
    case IpcCall::GetNamedLocations:
    case IpcCall::GetFolderContents:
    case IpcCall::GetPlaylists:
    case IpcCall::LoadPlaylist:
    case IpcCall::RenamePlaylist:
    case IpcCall::SavePlaylist:
    case IpcCall::DeletePlaylist:
    case IpcCall::SetPlaylists:
    case IpcCall::ClearHates:
    case IpcCall::ClearLikes:
    case IpcCall::ClearLocalOverrides:
    case IpcCall::FlushImageCache:
    case IpcCall::FlushMetadataCache:
    case IpcCall::GetHates:
    case IpcCall::GetLikes:
    case IpcCall::GetMediaInfo:
    case IpcCall::GetMusicDatabase:
    case IpcCall::Search:
    case IpcCall::SetHates:
    case IpcCall::SetLikes:
    case IpcCall::SetMediaInfo:
    case IpcCall::SetSaveMenu:
    case IpcCall::ShowFile:
    case IpcCall::ShowLocFromKey:
    case IpcCall::ShowMenu:
    case IpcCall::SubstrSearch:
    case IpcCall::TranscodingBegin:
    case IpcCall::UploadImage:
    case IpcCall::GetPicUri:
    case IpcCall::GetIgnoreList:
    case IpcCall::AddIgnoreItem:
    case IpcCall::RemoveIgnoreItem:
    case IpcCall::PushIgnoreList:
    case IpcCall::IgnoreListId:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
      return "Unknown";
    case IpcCall::ReadFromStorage:
      return "ReadFromStorage";
    case IpcCall::WriteToStorage:
      return "WriteToStorage";
    case IpcCall::DeleteFromStorage:
      return "DeleteFromStorage";
    case IpcCall::MinimizeWindow:
      return "MinimizeWindow";
    case IpcCall::MaximizeWindow:
      return "MaximizeWindow";
    case IpcCall::RestoreWindow:
      return "RestoreWindow";
    case IpcCall::CloseWindow:
      return "CloseWindow";
    case IpcCall::IsDev:
      return "IsDev";
    case IpcCall::AsyncData:
      return "AsyncData";
    case IpcCall::MenuAction:
      return "MenuAction";
    case IpcCall::ShowOpenDialog:
      return "ShowOpenDialog";
    case IpcCall::GetFileSystemRoots:
      return "GetFileSystemRoots";
    case IpcCall::GetNamedLocations:
      return "GetNamedLocations";
    case IpcCall::GetFolderContents:
      return "GetFolderContents";
    case IpcCall::GetPlaylists:
      return "GetPlaylists";
    case IpcCall::LoadPlaylist:
      return "LoadPlaylist";
    case IpcCall::RenamePlaylist:
      return "RenamePlaylist";
    case IpcCall::SavePlaylist:
      return "SavePlaylist";
    case IpcCall::DeletePlaylist:
      return "DeletePlaylist";
    case IpcCall::SetPlaylists:
      return "SetPlaylists";
    case IpcCall::ClearHates:
      return "ClearHates";
    case IpcCall::ClearLikes:
      return "ClearLikes";
    case IpcCall::ClearLocalOverrides:
      return "ClearLocalOverrides";
    case IpcCall::FlushImageCache:
      return "FlushImageCache";
    case IpcCall::FlushMetadataCache:
      return "FlushMetadataCache";
    case IpcCall::GetHates:
      return "GetHates";
    case IpcCall::GetLikes:
      return "GetLikes";
    case IpcCall::GetMediaInfo:
      return "GetMediaInfo";
    case IpcCall::GetMusicDatabase:
      return "GetMusicDatabase";
    case IpcCall::Search:
      return "Search";
    case IpcCall::SetHates:
      return "SetHates";
    case IpcCall::SetLikes:
      return "SetLikes";
    case IpcCall::SetMediaInfo:
      return "SetMediaInfo";
    case IpcCall::SetSaveMenu:
      return "SetSaveMenu";
    case IpcCall::ShowFile:
      return "ShowFile";
    case IpcCall::ShowLocFromKey:
      return "ShowLocFromKey";
    case IpcCall::ShowMenu:
      return "ShowMenu";
    case IpcCall::SubstrSearch:
      return "SubstrSearch";
    case IpcCall::TranscodingBegin:
      return "TranscodingBegin";
    case IpcCall::UploadImage:
      return "UploadImage";
    case IpcCall::GetPicUri:
      return "GetPicUri";
    case IpcCall::GetIgnoreList:
      return "GetIgnoreList";
    case IpcCall::AddIgnoreItem:
      return "AddIgnoreItem";
    case IpcCall::RemoveIgnoreItem:
      return "RemoveIgnoreItem";
    case IpcCall::PushIgnoreList:
      return "PushIgnoreList";
    case IpcCall::IgnoreListId:
      return "IgnoreListId";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
      return "0";
    case IpcCall::ReadFromStorage:
      return "1";
    case IpcCall::WriteToStorage:
      return "2";
    case IpcCall::DeleteFromStorage:
      return "3";
    case IpcCall::MinimizeWindow:
      return "4";
    case IpcCall::MaximizeWindow:
      return "5";
    case IpcCall::RestoreWindow:
      return "6";
    case IpcCall::CloseWindow:
      return "7";
    case IpcCall::IsDev:
      return "8";
    case IpcCall::AsyncData:
      return "9";
    case IpcCall::MenuAction:
      return "10";
    case IpcCall::ShowOpenDialog:
      return "11";
    case IpcCall::GetFileSystemRoots:
      return "12";
    case IpcCall::GetNamedLocations:
      return "13";
    case IpcCall::GetFolderContents:
      return "14";
    case IpcCall::GetPlaylists:
      return "1001";
    case IpcCall::LoadPlaylist:
      return "1002";
    case IpcCall::RenamePlaylist:
      return "1003";
    case IpcCall::SavePlaylist:
      return "1004";
    case IpcCall::DeletePlaylist:
      return "1005";
    case IpcCall::SetPlaylists:
      return "1006";
    case IpcCall::ClearHates:
      return "1007";
    case IpcCall::ClearLikes:
      return "1008";
    case IpcCall::ClearLocalOverrides:
      return "1009";
    case IpcCall::FlushImageCache:
      return "1010";
    case IpcCall::FlushMetadataCache:
      return "1011";
    case IpcCall::GetHates:
      return "1012";
    case IpcCall::GetLikes:
      return "1013";
    case IpcCall::GetMediaInfo:
      return "1014";
    case IpcCall::GetMusicDatabase:
      return "1015";
    case IpcCall::Search:
      return "1016";
    case IpcCall::SetHates:
      return "1017";
    case IpcCall::SetLikes:
      return "1018";
    case IpcCall::SetMediaInfo:
      return "1019";
    case IpcCall::SetSaveMenu:
      return "1020";
    case IpcCall::ShowFile:
      return "1021";
    case IpcCall::ShowLocFromKey:
      return "1022";
    case IpcCall::ShowMenu:
      return "1023";
    case IpcCall::SubstrSearch:
      return "1024";
    case IpcCall::TranscodingBegin:
      return "1025";
    case IpcCall::UploadImage:
      return "1026";
    case IpcCall::GetPicUri:
      return "1027";
    case IpcCall::GetIgnoreList:
      return "1028";
    case IpcCall::AddIgnoreItem:
      return "1029";
    case IpcCall::RemoveIgnoreItem:
      return "1030";
    case IpcCall::PushIgnoreList:
      return "1031";
    case IpcCall::IgnoreListId:
      return "1032";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<IpcCall> from_string<IpcCall>(
    std::string_view _str) {
  std::uint16_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  IpcCall _res = static_cast<IpcCall>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum IpcCall

#pragma region numeric enum SocketMsg
enum class SocketMsg : std::uint8_t {
  Unknown,
  ContentLoaded,
  KeepAlive,
  TranscodingUpdate,
  ManualRescan,
  RescanInProgress,
  RescanComplete,
  MusicDBUpdate
};

inline constexpr bool is_valid(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
    case SocketMsg::ContentLoaded:
    case SocketMsg::KeepAlive:
    case SocketMsg::TranscodingUpdate:
    case SocketMsg::ManualRescan:
    case SocketMsg::RescanInProgress:
    case SocketMsg::RescanComplete:
    case SocketMsg::MusicDBUpdate:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
      return "Unknown";
    case SocketMsg::ContentLoaded:
      return "ContentLoaded";
    case SocketMsg::KeepAlive:
      return "KeepAlive";
    case SocketMsg::TranscodingUpdate:
      return "TranscodingUpdate";
    case SocketMsg::ManualRescan:
      return "ManualRescan";
    case SocketMsg::RescanInProgress:
      return "RescanInProgress";
    case SocketMsg::RescanComplete:
      return "RescanComplete";
    case SocketMsg::MusicDBUpdate:
      return "MusicDBUpdate";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
      return "0";
    case SocketMsg::ContentLoaded:
      return "1";
    case SocketMsg::KeepAlive:
      return "2";
    case SocketMsg::TranscodingUpdate:
      return "3";
    case SocketMsg::ManualRescan:
      return "4";
    case SocketMsg::RescanInProgress:
      return "5";
    case SocketMsg::RescanComplete:
      return "6";
    case SocketMsg::MusicDBUpdate:
      return "7";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<SocketMsg> from_string<SocketMsg>(
    std::string_view _str) {
  std::uint8_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  SocketMsg _res = static_cast<SocketMsg>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum SocketMsg

#pragma region string enum StorageId

enum class StorageId {
  CurrentView,
  SettingValue,
  Shuffle,
  Repeat,
  CurrentIndex,
  Mute,
  Volume,
  PlaybackOrder,
  NowPlaying,
  CurrentSongList,
  Locations,
  DefaultLocation,
  OnlyPlayLikes,
  NeverPlayHates,
  FullAlbumsOnly,
  MinSongCount,
  LikedSongs,
  HatedSongs,
  SortWithArticles,
  DownloadAlbumArtwork,
  DownloadArtistArtwork,
  SaveAlbumArtworkWithMusic,
  AlbumCoverName,
  TranscodingUpdate,
  TranscodeSrcLocDir,
  TranscodeSrcLocPlaylist,
  TranscodeSrcLocArtist,
  TranscodeSrcLocAlbum,
  TranscodeDestLoc,
  TranscodeBitRate
};

inline constexpr bool is_valid(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
    case StorageId::SettingValue:
    case StorageId::Shuffle:
    case StorageId::Repeat:
    case StorageId::CurrentIndex:
    case StorageId::Mute:
    case StorageId::Volume:
    case StorageId::PlaybackOrder:
    case StorageId::NowPlaying:
    case StorageId::CurrentSongList:
    case StorageId::Locations:
    case StorageId::DefaultLocation:
    case StorageId::OnlyPlayLikes:
    case StorageId::NeverPlayHates:
    case StorageId::FullAlbumsOnly:
    case StorageId::MinSongCount:
    case StorageId::LikedSongs:
    case StorageId::HatedSongs:
    case StorageId::SortWithArticles:
    case StorageId::DownloadAlbumArtwork:
    case StorageId::DownloadArtistArtwork:
    case StorageId::SaveAlbumArtworkWithMusic:
    case StorageId::AlbumCoverName:
    case StorageId::TranscodingUpdate:
    case StorageId::TranscodeSrcLocDir:
    case StorageId::TranscodeSrcLocPlaylist:
    case StorageId::TranscodeSrcLocArtist:
    case StorageId::TranscodeSrcLocAlbum:
    case StorageId::TranscodeDestLoc:
    case StorageId::TranscodeBitRate:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
      return "currentView";
    case StorageId::SettingValue:
      return "someSetting";
    case StorageId::Shuffle:
      return "shuffle";
    case StorageId::Repeat:
      return "repeat";
    case StorageId::CurrentIndex:
      return "currentIndex";
    case StorageId::Mute:
      return "mute";
    case StorageId::Volume:
      return "volume";
    case StorageId::PlaybackOrder:
      return "playbackOrder";
    case StorageId::NowPlaying:
      return "nowPlaying";
    case StorageId::CurrentSongList:
      return "currentSongList";
    case StorageId::Locations:
      return "locations";
    case StorageId::DefaultLocation:
      return "defaultLocation";
    case StorageId::OnlyPlayLikes:
      return "onlyPlayLikes";
    case StorageId::NeverPlayHates:
      return "neverPlayHates";
    case StorageId::FullAlbumsOnly:
      return "fullAlbumsOnly";
    case StorageId::MinSongCount:
      return "minSongCount";
    case StorageId::LikedSongs:
      return "likedSongs";
    case StorageId::HatedSongs:
      return "hatedSongs";
    case StorageId::SortWithArticles:
      return "sortWithArticles";
    case StorageId::DownloadAlbumArtwork:
      return "downloadAlbumArtwork";
    case StorageId::DownloadArtistArtwork:
      return "downloadArtistArtwork";
    case StorageId::SaveAlbumArtworkWithMusic:
      return "saveAlbumArtworkWithMusic";
    case StorageId::AlbumCoverName:
      return "albumCoverName";
    case StorageId::TranscodingUpdate:
      return "getTranscodeUpdate";
    case StorageId::TranscodeSrcLocDir:
      return "transcodeSrcLocDir";
    case StorageId::TranscodeSrcLocPlaylist:
      return "transcodeSrcLocPlaylist";
    case StorageId::TranscodeSrcLocArtist:
      return "transcodeSrcLocArtist";
    case StorageId::TranscodeSrcLocAlbum:
      return "transcodeSrcLocAlbum";
    case StorageId::TranscodeDestLoc:
      return "transcodeDestLoc";
    case StorageId::TranscodeBitRate:
      return "transcodeBitRate";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StorageId> from_string<StorageId>(
    std::string_view str) {
  if (str == "currentView")
    return StorageId::CurrentView;
  if (str == "someSetting")
    return StorageId::SettingValue;
  if (str == "shuffle")
    return StorageId::Shuffle;
  if (str == "repeat")
    return StorageId::Repeat;
  if (str == "currentIndex")
    return StorageId::CurrentIndex;
  if (str == "mute")
    return StorageId::Mute;
  if (str == "volume")
    return StorageId::Volume;
  if (str == "playbackOrder")
    return StorageId::PlaybackOrder;
  if (str == "nowPlaying")
    return StorageId::NowPlaying;
  if (str == "currentSongList")
    return StorageId::CurrentSongList;
  if (str == "locations")
    return StorageId::Locations;
  if (str == "defaultLocation")
    return StorageId::DefaultLocation;
  if (str == "onlyPlayLikes")
    return StorageId::OnlyPlayLikes;
  if (str == "neverPlayHates")
    return StorageId::NeverPlayHates;
  if (str == "fullAlbumsOnly")
    return StorageId::FullAlbumsOnly;
  if (str == "minSongCount")
    return StorageId::MinSongCount;
  if (str == "likedSongs")
    return StorageId::LikedSongs;
  if (str == "hatedSongs")
    return StorageId::HatedSongs;
  if (str == "sortWithArticles")
    return StorageId::SortWithArticles;
  if (str == "downloadAlbumArtwork")
    return StorageId::DownloadAlbumArtwork;
  if (str == "downloadArtistArtwork")
    return StorageId::DownloadArtistArtwork;
  if (str == "saveAlbumArtworkWithMusic")
    return StorageId::SaveAlbumArtworkWithMusic;
  if (str == "albumCoverName")
    return StorageId::AlbumCoverName;
  if (str == "getTranscodeUpdate")
    return StorageId::TranscodingUpdate;
  if (str == "transcodeSrcLocDir")
    return StorageId::TranscodeSrcLocDir;
  if (str == "transcodeSrcLocPlaylist")
    return StorageId::TranscodeSrcLocPlaylist;
  if (str == "transcodeSrcLocArtist")
    return StorageId::TranscodeSrcLocArtist;
  if (str == "transcodeSrcLocAlbum")
    return StorageId::TranscodeSrcLocAlbum;
  if (str == "transcodeDestLoc")
    return StorageId::TranscodeDestLoc;
  if (str == "transcodeBitRate")
    return StorageId::TranscodeBitRate;
  return std::nullopt;
}

#pragma endregion string enum StorageId

struct MimeData {
  std::string type;
  std::string data;
};

struct FileFilterItem {
  std::string name;
  std::vector<std::string> extensions;
};

struct OpenDialogOptions {
  std::optional<bool> folder;
  std::optional<std::string> title;
  std::optional<std::string> defaultPath;
  std::optional<std::string> buttonLabel;
  std::optional<bool> multiSelections;
  std::optional<std::vector<FileFilterItem>> filters;
};
using NamedLocations = std::map<std::string, std::string>;

struct FileSystemItem {
  std::string file;
  double date;
  std::uint64_t size;
  std::string type;
};
using FolderContents = std::vector<FileSystemItem>;

#pragma region string enum IgnoreItemType

enum class IgnoreItemType { PathRoot, PathKeyword, DirName };

inline constexpr bool is_valid(IgnoreItemType _value) {
  switch (_value) {
    case IgnoreItemType::PathRoot:
    case IgnoreItemType::PathKeyword:
    case IgnoreItemType::DirName:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(IgnoreItemType _value) {
  switch (_value) {
    case IgnoreItemType::PathRoot:
      return "path-root";
    case IgnoreItemType::PathKeyword:
      return "path-keyword";
    case IgnoreItemType::DirName:
      return "dir-name";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<IgnoreItemType> from_string<IgnoreItemType>(
    std::string_view str) {
  if (str == "path-root")
    return IgnoreItemType::PathRoot;
  if (str == "path-keyword")
    return IgnoreItemType::PathKeyword;
  if (str == "dir-name")
    return IgnoreItemType::DirName;
  return std::nullopt;
}

#pragma endregion string enum IgnoreItemType

struct IgnoreItemPair {
  IgnoreItemType type;
  std::string value;
};

#pragma region string enum TranscodeFormatTargetName

enum class TranscodeFormatTargetName { m4a, mp3, aac };

inline constexpr bool is_valid(TranscodeFormatTargetName _value) {
  switch (_value) {
    case TranscodeFormatTargetName::m4a:
    case TranscodeFormatTargetName::mp3:
    case TranscodeFormatTargetName::aac:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(TranscodeFormatTargetName _value) {
  switch (_value) {
    case TranscodeFormatTargetName::m4a:
      return "m4a";
    case TranscodeFormatTargetName::mp3:
      return "mp3";
    case TranscodeFormatTargetName::aac:
      return "aac";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<TranscodeFormatTargetName>
from_string<TranscodeFormatTargetName>(std::string_view str) {
  if (str == "m4a")
    return TranscodeFormatTargetName::m4a;
  if (str == "mp3")
    return TranscodeFormatTargetName::mp3;
  if (str == "aac")
    return TranscodeFormatTargetName::aac;
  return std::nullopt;
}

#pragma endregion string enum TranscodeFormatTargetName

#pragma region string enum TranscodeSource

enum class TranscodeSource { Playlist, Artist, Album, Disk };

inline constexpr bool is_valid(TranscodeSource _value) {
  switch (_value) {
    case TranscodeSource::Playlist:
    case TranscodeSource::Artist:
    case TranscodeSource::Album:
    case TranscodeSource::Disk:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(TranscodeSource _value) {
  switch (_value) {
    case TranscodeSource::Playlist:
      return "p";
    case TranscodeSource::Artist:
      return "r";
    case TranscodeSource::Album:
      return "l";
    case TranscodeSource::Disk:
      return "d";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<TranscodeSource> from_string<TranscodeSource>(
    std::string_view str) {
  if (str == "p")
    return TranscodeSource::Playlist;
  if (str == "r")
    return TranscodeSource::Artist;
  if (str == "l")
    return TranscodeSource::Album;
  if (str == "d")
    return TranscodeSource::Disk;
  return std::nullopt;
}

#pragma endregion string enum TranscodeSource

struct TranscodeSourceLocation {
  TranscodeSource type;
  std::string loc;
};

struct FileFailure {
  std::string file;
  std::string error;
};

struct TranscodeState {
  std::string curStatus;
  std::vector<std::string> filesTranscoded;
  std::int32_t filesFound;
  std::int32_t filesPending;
  std::int32_t filesUntouched;
  std::vector<FileFailure> filesFailed;
  std::vector<std::string> itemsRemoved;
};

struct TranscodeInfo {
  TranscodeSourceLocation source;
  std::string dest;
  bool artwork;
  bool mirror;
  TranscodeFormatTargetName format;
  std::uint16_t bitrate;
};
using SongKey = std::string;
using AlbumKey = std::string;
using ArtistKey = std::string;
using MediaKey = std::string;
using PlaylistName = std::string;
using Playlist = std::vector<SongKey>;

struct Song {
  SongKey key;
  std::int16_t track;
  std::string title;
  AlbumKey albumId;
  std::vector<ArtistKey> artistIds;
  std::vector<ArtistKey> secondaryIds;
  std::vector<std::string> variations;
};

struct SongWithPath : public Song {
  std::string path;
};

#pragma region string enum VAType

enum class VAType { none, va, ost };

inline constexpr bool is_valid(VAType _value) {
  switch (_value) {
    case VAType::none:
    case VAType::va:
    case VAType::ost:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(VAType _value) {
  switch (_value) {
    case VAType::none:
      return "None";
    case VAType::va:
      return "VA";
    case VAType::ost:
      return "OST";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<VAType> from_string<VAType>(
    std::string_view str) {
  if (str == "None")
    return VAType::none;
  if (str == "VA")
    return VAType::va;
  if (str == "OST")
    return VAType::ost;
  return std::nullopt;
}

#pragma endregion string enum VAType

struct Artist {
  ArtistKey key;
  std::string name;
  std::vector<AlbumKey> albums;
  std::vector<SongKey> songs;
};

struct Album {
  AlbumKey key;
  std::int16_t year;
  std::string title;
  VAType vatype;
  std::vector<ArtistKey> primaryArtists;
  std::map<std::int16_t, SongKey> songs;
  std::vector<std::string> diskNames;
};

struct MediaInfo {
  std::map<std::string, std::string> general;
  std::map<std::string, std::string> audio;
};

struct SimpleMetadata {
  std::string artist;
  std::string album;
  std::int16_t year;
  std::int16_t track;
  std::string title;
  std::int16_t discNum;
  std::string discName;
  VAType compilation;
};

struct FullMetadata {
  std::string originalPath;
  std::vector<std::string> artist;
  std::string album;
  std::int16_t year;
  std::int16_t track;
  std::string title;
  VAType vaType;
  std::vector<std::string> moreArtists;
  std::vector<std::string> variations;
  std::int16_t disk;
  std::string diskName;
};

struct AudioFileRegexPattern {
  VAType compilation;
  std::string rgx;
};

struct MusicDatabase {
  std::unordered_map<ArtistKey, Artist> artists;
  std::unordered_map<AlbumKey, Album> albums;
  std::unordered_map<SongKey, Song> songs;
};

struct SearchResults {
  std::vector<SongKey> songs;
  std::vector<ArtistKey> artists;
  std::vector<AlbumKey> albums;
};

} // namespace Shared
#pragma region JSON serialization for string enum Keys
template <>
inline crow::json::wvalue to_json<Shared::Keys>(Shared::Keys _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::Keys> {
  static inline std::optional<Shared::Keys> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::Keys>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum Keys
#pragma region JSON serialization for string enum StrId
template <>
inline crow::json::wvalue to_json<Shared::StrId>(Shared::StrId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StrId> {
  static inline std::optional<Shared::StrId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StrId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StrId
#pragma region JSON serialization for string enum StorageId
template <>
inline crow::json::wvalue to_json<Shared::StorageId>(Shared::StorageId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StorageId> {
  static inline std::optional<Shared::StorageId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StorageId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StorageId

#pragma region JSON serialization for object MimeData
template <>
struct impl_to_json<Shared::MimeData> {
  static inline crow::json::wvalue process(const Shared::MimeData& _value) {
    crow::json::wvalue _res;
    _res["type"] = to_json(_value.type);
    _res["data"] = to_json(_value.data);

    return _res;
  }
};

template <>
inline std::optional<Shared::MimeData> from_json<Shared::MimeData>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MimeData _res;

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<std::string>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  if (!_value.has("data"))
    return std::nullopt;
  auto _data_opt_ = from_json<std::string>(_value["data"]);
  if (!_data_opt_.has_value())
    return std::nullopt;
  _res.data = std::move(*_data_opt_);

  return _res;
}
#pragma endregion JSON serialization for object MimeData

#pragma region JSON serialization for object FileFilterItem
template <>
struct impl_to_json<Shared::FileFilterItem> {
  static inline crow::json::wvalue process(
      const Shared::FileFilterItem& _value) {
    crow::json::wvalue _res;
    _res["name"] = to_json(_value.name);
    _res["extensions"] = to_json(_value.extensions);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileFilterItem> from_json<Shared::FileFilterItem>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileFilterItem _res;

  if (!_value.has("name"))
    return std::nullopt;
  auto _name_opt_ = from_json<std::string>(_value["name"]);
  if (!_name_opt_.has_value())
    return std::nullopt;
  _res.name = std::move(*_name_opt_);

  if (!_value.has("extensions"))
    return std::nullopt;
  auto _extensions_opt_ =
      from_json<std::vector<std::string>>(_value["extensions"]);
  if (!_extensions_opt_.has_value())
    return std::nullopt;
  _res.extensions = std::move(*_extensions_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileFilterItem

#pragma region JSON serialization for object OpenDialogOptions
template <>
struct impl_to_json<Shared::OpenDialogOptions> {
  static inline crow::json::wvalue process(
      const Shared::OpenDialogOptions& _value) {
    crow::json::wvalue _res;

    if (_value.folder) {
      _res["folder"] = to_json(*_value.folder);
    }
    if (_value.title) {
      _res["title"] = to_json(*_value.title);
    }
    if (_value.defaultPath) {
      _res["defaultPath"] = to_json(*_value.defaultPath);
    }
    if (_value.buttonLabel) {
      _res["buttonLabel"] = to_json(*_value.buttonLabel);
    }
    if (_value.multiSelections) {
      _res["multiSelections"] = to_json(*_value.multiSelections);
    }
    if (_value.filters) {
      _res["filters"] = to_json(*_value.filters);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::OpenDialogOptions>
from_json<Shared::OpenDialogOptions>(const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::OpenDialogOptions _res;

  if (_value.has("folder")) {
    auto _folder_opt_ = from_json<bool>(_value["folder"]);
    if (!_folder_opt_.has_value())
      return std::nullopt;
    _res.folder = std::move(*_folder_opt_);
  } else {
    _res.folder = std::nullopt;
  }

  if (_value.has("title")) {
    auto _title_opt_ = from_json<std::string>(_value["title"]);
    if (!_title_opt_.has_value())
      return std::nullopt;
    _res.title = std::move(*_title_opt_);
  } else {
    _res.title = std::nullopt;
  }

  if (_value.has("defaultPath")) {
    auto _defaultPath_opt_ = from_json<std::string>(_value["defaultPath"]);
    if (!_defaultPath_opt_.has_value())
      return std::nullopt;
    _res.defaultPath = std::move(*_defaultPath_opt_);
  } else {
    _res.defaultPath = std::nullopt;
  }

  if (_value.has("buttonLabel")) {
    auto _buttonLabel_opt_ = from_json<std::string>(_value["buttonLabel"]);
    if (!_buttonLabel_opt_.has_value())
      return std::nullopt;
    _res.buttonLabel = std::move(*_buttonLabel_opt_);
  } else {
    _res.buttonLabel = std::nullopt;
  }

  if (_value.has("multiSelections")) {
    auto _multiSelections_opt_ = from_json<bool>(_value["multiSelections"]);
    if (!_multiSelections_opt_.has_value())
      return std::nullopt;
    _res.multiSelections = std::move(*_multiSelections_opt_);
  } else {
    _res.multiSelections = std::nullopt;
  }

  if (_value.has("filters")) {
    auto _filters_opt_ =
        from_json<std::vector<Shared::FileFilterItem>>(_value["filters"]);
    if (!_filters_opt_.has_value())
      return std::nullopt;
    _res.filters = std::move(*_filters_opt_);
  } else {
    _res.filters = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object OpenDialogOptions

#pragma region JSON serialization for object FileSystemItem
template <>
struct impl_to_json<Shared::FileSystemItem> {
  static inline crow::json::wvalue process(
      const Shared::FileSystemItem& _value) {
    crow::json::wvalue _res;
    _res["file"] = to_json(_value.file);
    _res["date"] = to_json(_value.date);
    _res["size"] = to_json(_value.size);
    _res["type"] = to_json(_value.type);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileSystemItem> from_json<Shared::FileSystemItem>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileSystemItem _res;

  if (!_value.has("file"))
    return std::nullopt;
  auto _file_opt_ = from_json<std::string>(_value["file"]);
  if (!_file_opt_.has_value())
    return std::nullopt;
  _res.file = std::move(*_file_opt_);

  if (!_value.has("date"))
    return std::nullopt;
  auto _date_opt_ = from_json<double>(_value["date"]);
  if (!_date_opt_.has_value())
    return std::nullopt;
  _res.date = std::move(*_date_opt_);

  if (!_value.has("size"))
    return std::nullopt;
  auto _size_opt_ = from_json<std::uint64_t>(_value["size"]);
  if (!_size_opt_.has_value())
    return std::nullopt;
  _res.size = std::move(*_size_opt_);

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<std::string>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileSystemItem
#pragma region JSON serialization for string enum IgnoreItemType
template <>
inline crow::json::wvalue to_json<Shared::IgnoreItemType>(
    Shared::IgnoreItemType _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::IgnoreItemType> {
  static inline std::optional<Shared::IgnoreItemType> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::IgnoreItemType>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum IgnoreItemType

#pragma region JSON serialization for object IgnoreItemPair
template <>
struct impl_to_json<Shared::IgnoreItemPair> {
  static inline crow::json::wvalue process(
      const Shared::IgnoreItemPair& _value) {
    crow::json::wvalue _res;
    _res["type"] = to_json(_value.type);
    _res["value"] = to_json(_value.value);

    return _res;
  }
};

template <>
inline std::optional<Shared::IgnoreItemPair> from_json<Shared::IgnoreItemPair>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::IgnoreItemPair _res;

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<Shared::IgnoreItemType>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  if (!_value.has("value"))
    return std::nullopt;
  auto _value_opt_ = from_json<std::string>(_value["value"]);
  if (!_value_opt_.has_value())
    return std::nullopt;
  _res.value = std::move(*_value_opt_);

  return _res;
}
#pragma endregion JSON serialization for object IgnoreItemPair
#pragma region JSON serialization for string enum TranscodeFormatTargetName
template <>
inline crow::json::wvalue to_json<Shared::TranscodeFormatTargetName>(
    Shared::TranscodeFormatTargetName _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::TranscodeFormatTargetName> {
  static inline std::optional<Shared::TranscodeFormatTargetName> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::TranscodeFormatTargetName>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum TranscodeFormatTargetName
#pragma region JSON serialization for string enum TranscodeSource
template <>
inline crow::json::wvalue to_json<Shared::TranscodeSource>(
    Shared::TranscodeSource _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::TranscodeSource> {
  static inline std::optional<Shared::TranscodeSource> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::TranscodeSource>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum TranscodeSource

#pragma region JSON serialization for object TranscodeSourceLocation
template <>
struct impl_to_json<Shared::TranscodeSourceLocation> {
  static inline crow::json::wvalue process(
      const Shared::TranscodeSourceLocation& _value) {
    crow::json::wvalue _res;
    _res["type"] = to_json(_value.type);
    _res["loc"] = to_json(_value.loc);

    return _res;
  }
};

template <>
inline std::optional<Shared::TranscodeSourceLocation>
from_json<Shared::TranscodeSourceLocation>(const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::TranscodeSourceLocation _res;

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<Shared::TranscodeSource>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  if (!_value.has("loc"))
    return std::nullopt;
  auto _loc_opt_ = from_json<std::string>(_value["loc"]);
  if (!_loc_opt_.has_value())
    return std::nullopt;
  _res.loc = std::move(*_loc_opt_);

  return _res;
}
#pragma endregion JSON serialization for object TranscodeSourceLocation

#pragma region JSON serialization for object FileFailure
template <>
struct impl_to_json<Shared::FileFailure> {
  static inline crow::json::wvalue process(const Shared::FileFailure& _value) {
    crow::json::wvalue _res;
    _res["file"] = to_json(_value.file);
    _res["error"] = to_json(_value.error);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileFailure> from_json<Shared::FileFailure>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileFailure _res;

  if (!_value.has("file"))
    return std::nullopt;
  auto _file_opt_ = from_json<std::string>(_value["file"]);
  if (!_file_opt_.has_value())
    return std::nullopt;
  _res.file = std::move(*_file_opt_);

  if (!_value.has("error"))
    return std::nullopt;
  auto _error_opt_ = from_json<std::string>(_value["error"]);
  if (!_error_opt_.has_value())
    return std::nullopt;
  _res.error = std::move(*_error_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileFailure

#pragma region JSON serialization for object TranscodeState
template <>
struct impl_to_json<Shared::TranscodeState> {
  static inline crow::json::wvalue process(
      const Shared::TranscodeState& _value) {
    crow::json::wvalue _res;
    _res["curStatus"] = to_json(_value.curStatus);
    _res["filesTranscoded"] = to_json(_value.filesTranscoded);
    _res["filesFound"] = to_json(_value.filesFound);
    _res["filesPending"] = to_json(_value.filesPending);
    _res["filesUntouched"] = to_json(_value.filesUntouched);
    _res["filesFailed"] = to_json(_value.filesFailed);
    _res["itemsRemoved"] = to_json(_value.itemsRemoved);

    return _res;
  }
};

template <>
inline std::optional<Shared::TranscodeState> from_json<Shared::TranscodeState>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::TranscodeState _res;

  if (!_value.has("curStatus"))
    return std::nullopt;
  auto _curStatus_opt_ = from_json<std::string>(_value["curStatus"]);
  if (!_curStatus_opt_.has_value())
    return std::nullopt;
  _res.curStatus = std::move(*_curStatus_opt_);

  if (!_value.has("filesTranscoded"))
    return std::nullopt;
  auto _filesTranscoded_opt_ =
      from_json<std::vector<std::string>>(_value["filesTranscoded"]);
  if (!_filesTranscoded_opt_.has_value())
    return std::nullopt;
  _res.filesTranscoded = std::move(*_filesTranscoded_opt_);

  if (!_value.has("filesFound"))
    return std::nullopt;
  auto _filesFound_opt_ = from_json<std::int32_t>(_value["filesFound"]);
  if (!_filesFound_opt_.has_value())
    return std::nullopt;
  _res.filesFound = std::move(*_filesFound_opt_);

  if (!_value.has("filesPending"))
    return std::nullopt;
  auto _filesPending_opt_ = from_json<std::int32_t>(_value["filesPending"]);
  if (!_filesPending_opt_.has_value())
    return std::nullopt;
  _res.filesPending = std::move(*_filesPending_opt_);

  if (!_value.has("filesUntouched"))
    return std::nullopt;
  auto _filesUntouched_opt_ = from_json<std::int32_t>(_value["filesUntouched"]);
  if (!_filesUntouched_opt_.has_value())
    return std::nullopt;
  _res.filesUntouched = std::move(*_filesUntouched_opt_);

  if (!_value.has("filesFailed"))
    return std::nullopt;
  auto _filesFailed_opt_ =
      from_json<std::vector<Shared::FileFailure>>(_value["filesFailed"]);
  if (!_filesFailed_opt_.has_value())
    return std::nullopt;
  _res.filesFailed = std::move(*_filesFailed_opt_);

  if (!_value.has("itemsRemoved"))
    return std::nullopt;
  auto _itemsRemoved_opt_ =
      from_json<std::vector<std::string>>(_value["itemsRemoved"]);
  if (!_itemsRemoved_opt_.has_value())
    return std::nullopt;
  _res.itemsRemoved = std::move(*_itemsRemoved_opt_);

  return _res;
}
#pragma endregion JSON serialization for object TranscodeState

#pragma region JSON serialization for object TranscodeInfo
template <>
struct impl_to_json<Shared::TranscodeInfo> {
  static inline crow::json::wvalue process(
      const Shared::TranscodeInfo& _value) {
    crow::json::wvalue _res;
    _res["source"] = to_json(_value.source);
    _res["dest"] = to_json(_value.dest);
    _res["artwork"] = to_json(_value.artwork);
    _res["mirror"] = to_json(_value.mirror);
    _res["format"] = to_json(_value.format);
    _res["bitrate"] = to_json(_value.bitrate);

    return _res;
  }
};

template <>
inline std::optional<Shared::TranscodeInfo> from_json<Shared::TranscodeInfo>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::TranscodeInfo _res;

  if (!_value.has("source"))
    return std::nullopt;
  auto _source_opt_ =
      from_json<Shared::TranscodeSourceLocation>(_value["source"]);
  if (!_source_opt_.has_value())
    return std::nullopt;
  _res.source = std::move(*_source_opt_);

  if (!_value.has("dest"))
    return std::nullopt;
  auto _dest_opt_ = from_json<std::string>(_value["dest"]);
  if (!_dest_opt_.has_value())
    return std::nullopt;
  _res.dest = std::move(*_dest_opt_);

  if (!_value.has("artwork"))
    return std::nullopt;
  auto _artwork_opt_ = from_json<bool>(_value["artwork"]);
  if (!_artwork_opt_.has_value())
    return std::nullopt;
  _res.artwork = std::move(*_artwork_opt_);

  if (!_value.has("mirror"))
    return std::nullopt;
  auto _mirror_opt_ = from_json<bool>(_value["mirror"]);
  if (!_mirror_opt_.has_value())
    return std::nullopt;
  _res.mirror = std::move(*_mirror_opt_);

  if (!_value.has("format"))
    return std::nullopt;
  auto _format_opt_ =
      from_json<Shared::TranscodeFormatTargetName>(_value["format"]);
  if (!_format_opt_.has_value())
    return std::nullopt;
  _res.format = std::move(*_format_opt_);

  if (!_value.has("bitrate"))
    return std::nullopt;
  auto _bitrate_opt_ = from_json<std::uint16_t>(_value["bitrate"]);
  if (!_bitrate_opt_.has_value())
    return std::nullopt;
  _res.bitrate = std::move(*_bitrate_opt_);

  return _res;
}
#pragma endregion JSON serialization for object TranscodeInfo

#pragma region JSON serialization for object Song
template <>
struct impl_to_json<Shared::Song> {
  static inline crow::json::wvalue process(const Shared::Song& _value) {
    crow::json::wvalue _res;
    _res["key"] = to_json(_value.key);
    _res["track"] = to_json(_value.track);
    _res["title"] = to_json(_value.title);
    _res["albumId"] = to_json(_value.albumId);
    _res["artistIds"] = to_json(_value.artistIds);
    _res["secondaryIds"] = to_json(_value.secondaryIds);
    _res["variations"] = to_json(_value.variations);

    return _res;
  }
};

template <>
inline std::optional<Shared::Song> from_json<Shared::Song>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Song _res;

  if (!_value.has("key"))
    return std::nullopt;
  auto _key_opt_ = from_json<Shared::SongKey>(_value["key"]);
  if (!_key_opt_.has_value())
    return std::nullopt;
  _res.key = std::move(*_key_opt_);

  if (!_value.has("track"))
    return std::nullopt;
  auto _track_opt_ = from_json<std::int16_t>(_value["track"]);
  if (!_track_opt_.has_value())
    return std::nullopt;
  _res.track = std::move(*_track_opt_);

  if (!_value.has("title"))
    return std::nullopt;
  auto _title_opt_ = from_json<std::string>(_value["title"]);
  if (!_title_opt_.has_value())
    return std::nullopt;
  _res.title = std::move(*_title_opt_);

  if (!_value.has("albumId"))
    return std::nullopt;
  auto _albumId_opt_ = from_json<Shared::AlbumKey>(_value["albumId"]);
  if (!_albumId_opt_.has_value())
    return std::nullopt;
  _res.albumId = std::move(*_albumId_opt_);

  if (!_value.has("artistIds"))
    return std::nullopt;
  auto _artistIds_opt_ =
      from_json<std::vector<Shared::ArtistKey>>(_value["artistIds"]);
  if (!_artistIds_opt_.has_value())
    return std::nullopt;
  _res.artistIds = std::move(*_artistIds_opt_);

  if (!_value.has("secondaryIds"))
    return std::nullopt;
  auto _secondaryIds_opt_ =
      from_json<std::vector<Shared::ArtistKey>>(_value["secondaryIds"]);
  if (!_secondaryIds_opt_.has_value())
    return std::nullopt;
  _res.secondaryIds = std::move(*_secondaryIds_opt_);

  if (!_value.has("variations"))
    return std::nullopt;
  auto _variations_opt_ =
      from_json<std::vector<std::string>>(_value["variations"]);
  if (!_variations_opt_.has_value())
    return std::nullopt;
  _res.variations = std::move(*_variations_opt_);

  return _res;
}
#pragma endregion JSON serialization for object Song

#pragma region JSON serialization for object SongWithPath
template <>
struct impl_to_json<Shared::SongWithPath> {
  static inline crow::json::wvalue process(const Shared::SongWithPath& _value) {
    crow::json::wvalue _res = impl_to_json<Shared::Song>::process(_value);
    _res["path"] = to_json(_value.path);
    return _res;
  }
};

template <>
inline std::optional<Shared::SongWithPath> from_json<Shared::SongWithPath>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  std::optional<Shared::Song> _base = from_json<Shared::Song>(_value);
  if (!_base.has_value())
    return std::nullopt;

  if (!_value.has("path"))
    return std::nullopt;
  auto _path_opt_ = from_json<std::string>(_value["path"]);
  if (!_path_opt_.has_value())
    return std::nullopt;
  Shared::SongWithPath _res{std::move(*_base), std::move(*_path_opt_)};

  return _res;
}
#pragma endregion JSON serialization for object SongWithPath
#pragma region JSON serialization for string enum VAType
template <>
inline crow::json::wvalue to_json<Shared::VAType>(Shared::VAType _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::VAType> {
  static inline std::optional<Shared::VAType> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::VAType>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum VAType

#pragma region JSON serialization for object Artist
template <>
struct impl_to_json<Shared::Artist> {
  static inline crow::json::wvalue process(const Shared::Artist& _value) {
    crow::json::wvalue _res;
    _res["key"] = to_json(_value.key);
    _res["name"] = to_json(_value.name);
    _res["albums"] = to_json(_value.albums);
    _res["songs"] = to_json(_value.songs);

    return _res;
  }
};

template <>
inline std::optional<Shared::Artist> from_json<Shared::Artist>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Artist _res;

  if (!_value.has("key"))
    return std::nullopt;
  auto _key_opt_ = from_json<Shared::ArtistKey>(_value["key"]);
  if (!_key_opt_.has_value())
    return std::nullopt;
  _res.key = std::move(*_key_opt_);

  if (!_value.has("name"))
    return std::nullopt;
  auto _name_opt_ = from_json<std::string>(_value["name"]);
  if (!_name_opt_.has_value())
    return std::nullopt;
  _res.name = std::move(*_name_opt_);

  if (!_value.has("albums"))
    return std::nullopt;
  auto _albums_opt_ =
      from_json<std::vector<Shared::AlbumKey>>(_value["albums"]);
  if (!_albums_opt_.has_value())
    return std::nullopt;
  _res.albums = std::move(*_albums_opt_);

  if (!_value.has("songs"))
    return std::nullopt;
  auto _songs_opt_ = from_json<std::vector<Shared::SongKey>>(_value["songs"]);
  if (!_songs_opt_.has_value())
    return std::nullopt;
  _res.songs = std::move(*_songs_opt_);

  return _res;
}
#pragma endregion JSON serialization for object Artist

#pragma region JSON serialization for object Album
template <>
struct impl_to_json<Shared::Album> {
  static inline crow::json::wvalue process(const Shared::Album& _value) {
    crow::json::wvalue _res;
    _res["key"] = to_json(_value.key);
    _res["year"] = to_json(_value.year);
    _res["title"] = to_json(_value.title);
    _res["vatype"] = to_json(_value.vatype);
    _res["primaryArtists"] = to_json(_value.primaryArtists);
    _res["songs"] = to_json(_value.songs);
    _res["diskNames"] = to_json(_value.diskNames);

    return _res;
  }
};

template <>
inline std::optional<Shared::Album> from_json<Shared::Album>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Album _res;

  if (!_value.has("key"))
    return std::nullopt;
  auto _key_opt_ = from_json<Shared::AlbumKey>(_value["key"]);
  if (!_key_opt_.has_value())
    return std::nullopt;
  _res.key = std::move(*_key_opt_);

  if (!_value.has("year"))
    return std::nullopt;
  auto _year_opt_ = from_json<std::int16_t>(_value["year"]);
  if (!_year_opt_.has_value())
    return std::nullopt;
  _res.year = std::move(*_year_opt_);

  if (!_value.has("title"))
    return std::nullopt;
  auto _title_opt_ = from_json<std::string>(_value["title"]);
  if (!_title_opt_.has_value())
    return std::nullopt;
  _res.title = std::move(*_title_opt_);

  if (!_value.has("vatype"))
    return std::nullopt;
  auto _vatype_opt_ = from_json<Shared::VAType>(_value["vatype"]);
  if (!_vatype_opt_.has_value())
    return std::nullopt;
  _res.vatype = std::move(*_vatype_opt_);

  if (!_value.has("primaryArtists"))
    return std::nullopt;
  auto _primaryArtists_opt_ =
      from_json<std::vector<Shared::ArtistKey>>(_value["primaryArtists"]);
  if (!_primaryArtists_opt_.has_value())
    return std::nullopt;
  _res.primaryArtists = std::move(*_primaryArtists_opt_);

  if (!_value.has("songs"))
    return std::nullopt;
  auto _songs_opt_ =
      from_json<std::map<std::int16_t, Shared::SongKey>>(_value["songs"]);
  if (!_songs_opt_.has_value())
    return std::nullopt;
  _res.songs = std::move(*_songs_opt_);

  if (!_value.has("diskNames"))
    return std::nullopt;
  auto _diskNames_opt_ =
      from_json<std::vector<std::string>>(_value["diskNames"]);
  if (!_diskNames_opt_.has_value())
    return std::nullopt;
  _res.diskNames = std::move(*_diskNames_opt_);

  return _res;
}
#pragma endregion JSON serialization for object Album

#pragma region JSON serialization for object MediaInfo
template <>
struct impl_to_json<Shared::MediaInfo> {
  static inline crow::json::wvalue process(const Shared::MediaInfo& _value) {
    crow::json::wvalue _res;
    _res["general"] = to_json(_value.general);
    _res["audio"] = to_json(_value.audio);

    return _res;
  }
};

template <>
inline std::optional<Shared::MediaInfo> from_json<Shared::MediaInfo>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MediaInfo _res;

  if (!_value.has("general"))
    return std::nullopt;
  auto _general_opt_ =
      from_json<std::map<std::string, std::string>>(_value["general"]);
  if (!_general_opt_.has_value())
    return std::nullopt;
  _res.general = std::move(*_general_opt_);

  if (!_value.has("audio"))
    return std::nullopt;
  auto _audio_opt_ =
      from_json<std::map<std::string, std::string>>(_value["audio"]);
  if (!_audio_opt_.has_value())
    return std::nullopt;
  _res.audio = std::move(*_audio_opt_);

  return _res;
}
#pragma endregion JSON serialization for object MediaInfo

#pragma region JSON serialization for object SimpleMetadata
template <>
struct impl_to_json<Shared::SimpleMetadata> {
  static inline crow::json::wvalue process(
      const Shared::SimpleMetadata& _value) {
    crow::json::wvalue _res;
    _res["artist"] = to_json(_value.artist);
    _res["album"] = to_json(_value.album);
    _res["year"] = to_json(_value.year);
    _res["track"] = to_json(_value.track);
    _res["title"] = to_json(_value.title);
    _res["discNum"] = to_json(_value.discNum);
    _res["discName"] = to_json(_value.discName);
    _res["compilation"] = to_json(_value.compilation);

    return _res;
  }
};

template <>
inline std::optional<Shared::SimpleMetadata> from_json<Shared::SimpleMetadata>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::SimpleMetadata _res;

  if (!_value.has("artist"))
    return std::nullopt;
  auto _artist_opt_ = from_json<std::string>(_value["artist"]);
  if (!_artist_opt_.has_value())
    return std::nullopt;
  _res.artist = std::move(*_artist_opt_);

  if (!_value.has("album"))
    return std::nullopt;
  auto _album_opt_ = from_json<std::string>(_value["album"]);
  if (!_album_opt_.has_value())
    return std::nullopt;
  _res.album = std::move(*_album_opt_);

  if (!_value.has("year"))
    return std::nullopt;
  auto _year_opt_ = from_json<std::int16_t>(_value["year"]);
  if (!_year_opt_.has_value())
    return std::nullopt;
  _res.year = std::move(*_year_opt_);

  if (!_value.has("track"))
    return std::nullopt;
  auto _track_opt_ = from_json<std::int16_t>(_value["track"]);
  if (!_track_opt_.has_value())
    return std::nullopt;
  _res.track = std::move(*_track_opt_);

  if (!_value.has("title"))
    return std::nullopt;
  auto _title_opt_ = from_json<std::string>(_value["title"]);
  if (!_title_opt_.has_value())
    return std::nullopt;
  _res.title = std::move(*_title_opt_);

  if (!_value.has("discNum"))
    return std::nullopt;
  auto _discNum_opt_ = from_json<std::int16_t>(_value["discNum"]);
  if (!_discNum_opt_.has_value())
    return std::nullopt;
  _res.discNum = std::move(*_discNum_opt_);

  if (!_value.has("discName"))
    return std::nullopt;
  auto _discName_opt_ = from_json<std::string>(_value["discName"]);
  if (!_discName_opt_.has_value())
    return std::nullopt;
  _res.discName = std::move(*_discName_opt_);

  if (!_value.has("compilation"))
    return std::nullopt;
  auto _compilation_opt_ = from_json<Shared::VAType>(_value["compilation"]);
  if (!_compilation_opt_.has_value())
    return std::nullopt;
  _res.compilation = std::move(*_compilation_opt_);

  return _res;
}
#pragma endregion JSON serialization for object SimpleMetadata

#pragma region JSON serialization for object FullMetadata
template <>
struct impl_to_json<Shared::FullMetadata> {
  static inline crow::json::wvalue process(const Shared::FullMetadata& _value) {
    crow::json::wvalue _res;
    _res["originalPath"] = to_json(_value.originalPath);
    _res["artist"] = to_json(_value.artist);
    _res["album"] = to_json(_value.album);
    _res["year"] = to_json(_value.year);
    _res["track"] = to_json(_value.track);
    _res["title"] = to_json(_value.title);
    _res["vaType"] = to_json(_value.vaType);
    _res["moreArtists"] = to_json(_value.moreArtists);
    _res["variations"] = to_json(_value.variations);
    _res["disk"] = to_json(_value.disk);
    _res["diskName"] = to_json(_value.diskName);

    return _res;
  }
};

template <>
inline std::optional<Shared::FullMetadata> from_json<Shared::FullMetadata>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FullMetadata _res;

  if (!_value.has("originalPath"))
    return std::nullopt;
  auto _originalPath_opt_ = from_json<std::string>(_value["originalPath"]);
  if (!_originalPath_opt_.has_value())
    return std::nullopt;
  _res.originalPath = std::move(*_originalPath_opt_);

  if (!_value.has("artist"))
    return std::nullopt;
  auto _artist_opt_ = from_json<std::vector<std::string>>(_value["artist"]);
  if (!_artist_opt_.has_value())
    return std::nullopt;
  _res.artist = std::move(*_artist_opt_);

  if (!_value.has("album"))
    return std::nullopt;
  auto _album_opt_ = from_json<std::string>(_value["album"]);
  if (!_album_opt_.has_value())
    return std::nullopt;
  _res.album = std::move(*_album_opt_);

  if (!_value.has("year"))
    return std::nullopt;
  auto _year_opt_ = from_json<std::int16_t>(_value["year"]);
  if (!_year_opt_.has_value())
    return std::nullopt;
  _res.year = std::move(*_year_opt_);

  if (!_value.has("track"))
    return std::nullopt;
  auto _track_opt_ = from_json<std::int16_t>(_value["track"]);
  if (!_track_opt_.has_value())
    return std::nullopt;
  _res.track = std::move(*_track_opt_);

  if (!_value.has("title"))
    return std::nullopt;
  auto _title_opt_ = from_json<std::string>(_value["title"]);
  if (!_title_opt_.has_value())
    return std::nullopt;
  _res.title = std::move(*_title_opt_);

  if (!_value.has("vaType"))
    return std::nullopt;
  auto _vaType_opt_ = from_json<Shared::VAType>(_value["vaType"]);
  if (!_vaType_opt_.has_value())
    return std::nullopt;
  _res.vaType = std::move(*_vaType_opt_);

  if (!_value.has("moreArtists"))
    return std::nullopt;
  auto _moreArtists_opt_ =
      from_json<std::vector<std::string>>(_value["moreArtists"]);
  if (!_moreArtists_opt_.has_value())
    return std::nullopt;
  _res.moreArtists = std::move(*_moreArtists_opt_);

  if (!_value.has("variations"))
    return std::nullopt;
  auto _variations_opt_ =
      from_json<std::vector<std::string>>(_value["variations"]);
  if (!_variations_opt_.has_value())
    return std::nullopt;
  _res.variations = std::move(*_variations_opt_);

  if (!_value.has("disk"))
    return std::nullopt;
  auto _disk_opt_ = from_json<std::int16_t>(_value["disk"]);
  if (!_disk_opt_.has_value())
    return std::nullopt;
  _res.disk = std::move(*_disk_opt_);

  if (!_value.has("diskName"))
    return std::nullopt;
  auto _diskName_opt_ = from_json<std::string>(_value["diskName"]);
  if (!_diskName_opt_.has_value())
    return std::nullopt;
  _res.diskName = std::move(*_diskName_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FullMetadata

#pragma region JSON serialization for object AudioFileRegexPattern
template <>
struct impl_to_json<Shared::AudioFileRegexPattern> {
  static inline crow::json::wvalue process(
      const Shared::AudioFileRegexPattern& _value) {
    crow::json::wvalue _res;
    _res["compilation"] = to_json(_value.compilation);
    _res["rgx"] = to_json(_value.rgx);

    return _res;
  }
};

template <>
inline std::optional<Shared::AudioFileRegexPattern>
from_json<Shared::AudioFileRegexPattern>(const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::AudioFileRegexPattern _res;

  if (!_value.has("compilation"))
    return std::nullopt;
  auto _compilation_opt_ = from_json<Shared::VAType>(_value["compilation"]);
  if (!_compilation_opt_.has_value())
    return std::nullopt;
  _res.compilation = std::move(*_compilation_opt_);

  if (!_value.has("rgx"))
    return std::nullopt;
  auto _rgx_opt_ = from_json<std::string>(_value["rgx"]);
  if (!_rgx_opt_.has_value())
    return std::nullopt;
  _res.rgx = std::move(*_rgx_opt_);

  return _res;
}
#pragma endregion JSON serialization for object AudioFileRegexPattern

#pragma region JSON serialization for object MusicDatabase
template <>
struct impl_to_json<Shared::MusicDatabase> {
  static inline crow::json::wvalue process(
      const Shared::MusicDatabase& _value) {
    crow::json::wvalue _res;
    _res["artists"] = to_json(_value.artists);
    _res["albums"] = to_json(_value.albums);
    _res["songs"] = to_json(_value.songs);

    return _res;
  }
};

template <>
inline std::optional<Shared::MusicDatabase> from_json<Shared::MusicDatabase>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MusicDatabase _res;

  if (!_value.has("artists"))
    return std::nullopt;
  auto _artists_opt_ =
      from_json<std::unordered_map<Shared::ArtistKey, Shared::Artist>>(
          _value["artists"]);
  if (!_artists_opt_.has_value())
    return std::nullopt;
  _res.artists = std::move(*_artists_opt_);

  if (!_value.has("albums"))
    return std::nullopt;
  auto _albums_opt_ =
      from_json<std::unordered_map<Shared::AlbumKey, Shared::Album>>(
          _value["albums"]);
  if (!_albums_opt_.has_value())
    return std::nullopt;
  _res.albums = std::move(*_albums_opt_);

  if (!_value.has("songs"))
    return std::nullopt;
  auto _songs_opt_ =
      from_json<std::unordered_map<Shared::SongKey, Shared::Song>>(
          _value["songs"]);
  if (!_songs_opt_.has_value())
    return std::nullopt;
  _res.songs = std::move(*_songs_opt_);

  return _res;
}
#pragma endregion JSON serialization for object MusicDatabase

#pragma region JSON serialization for object SearchResults
template <>
struct impl_to_json<Shared::SearchResults> {
  static inline crow::json::wvalue process(
      const Shared::SearchResults& _value) {
    crow::json::wvalue _res;
    _res["songs"] = to_json(_value.songs);
    _res["artists"] = to_json(_value.artists);
    _res["albums"] = to_json(_value.albums);

    return _res;
  }
};

template <>
inline std::optional<Shared::SearchResults> from_json<Shared::SearchResults>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::SearchResults _res;

  if (!_value.has("songs"))
    return std::nullopt;
  auto _songs_opt_ = from_json<std::vector<Shared::SongKey>>(_value["songs"]);
  if (!_songs_opt_.has_value())
    return std::nullopt;
  _res.songs = std::move(*_songs_opt_);

  if (!_value.has("artists"))
    return std::nullopt;
  auto _artists_opt_ =
      from_json<std::vector<Shared::ArtistKey>>(_value["artists"]);
  if (!_artists_opt_.has_value())
    return std::nullopt;
  _res.artists = std::move(*_artists_opt_);

  if (!_value.has("albums"))
    return std::nullopt;
  auto _albums_opt_ =
      from_json<std::vector<Shared::AlbumKey>>(_value["albums"]);
  if (!_albums_opt_.has_value())
    return std::nullopt;
  _res.albums = std::move(*_albums_opt_);

  return _res;
}
#pragma endregion JSON serialization for object SearchResults
