import {
  ArrType,
  Enum,
  MapType,
  NEnum,
  ObjType,
  SEnum,
  SetType,
  SubType,
  TupType,
  Types,
  isArrayType,
  isBoolType,
  isCharType,
  isDoubleType,
  isEnumType,
  isFastMapType,
  isFastSetType,
  isFloatType,
  isI16Type,
  isI32Type,
  isI64Type,
  isI8Type,
  isMapType,
  isObjectType,
  isRefType,
  isSetType,
  isStringType,
  isSubType,
  isTupleType,
  isU16Type,
  isU32Type,
  isU64Type,
  isU8Type,
} from '../../www/Shared/IDL';
import { EmitItem, Emitter, FileGenerator, MakeGenerator } from './api';

function SingleQuoteSafe(str: string): string {
  // Escape single quotes in the string for TypeScript
  return str.replace(/'/g, "\\'");
}

async function header(writer: Bun.FileSink): Promise<void> {
  await writer.write(`// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from www/Shared/Definitions.ts by running 'bun gen'
// If you need to change this file, edit www/Shared/Definitions.ts and run
// 'bun gen' again. Or, if you need to change the generation process, edit
// scripts/emitters/typescript.ts and run 'bun gen' again.
// DO NOT EDIT THIS FILE DIRECTLY!!!
 
import * as TypeChk from '@freik/typechk';

`);
}

async function footer(writer: Bun.FileSink): Promise<void> {
  await writer.write(`
// End of generated code
`);
}

function getTypeName(type: Types): string {
  if (
    isU8Type(type) ||
    isI8Type(type) ||
    isU16Type(type) ||
    isI16Type(type) ||
    isU32Type(type) ||
    isI32Type(type) ||
    isFloatType(type) ||
    isDoubleType(type)
  ) {
    return 'number';
  } else if (isU64Type(type) || isI64Type(type)) {
    return 'BigInt';
  } else if (isStringType(type) || isCharType(type)) {
    return 'string';
  } else if (isBoolType(type)) {
    return 'boolean';
  } else if (isRefType(type)) {
    return type.r; // Reference type, just return the name
  } else if (isArrayType(type)) {
    return `${getTypeName(type.d)}[]`;
  } else if (isSetType(type) || isFastSetType(type)) {
    return `Set<${getTypeName(type.d)}>`;
  } else if (isMapType(type) || isFastMapType(type)) {
    return `Map<${getTypeName(type.k)}, ${getTypeName(type.v)}>`;
  } else if (isTupleType(type)) {
    return `[${type.l.map(getTypeName).join(', ')}]`;
  }
  throw new Error(`Unsupported unnamed type: ${JSON.stringify(type)}`);
}

function getTypeCheckName(type: Types): string {
  if (isU8Type(type)) { 
    return "chkIdlU8";
  } else if (isI8Type(type)) {
    return "chkIdlI8";
  } else if (isU16Type(type)) {
    return "chkIdlU16";
  } else if (isI16Type(type)) {
    return "chkIdlI16";
  } else if (isU32Type(type)) {
    return "chkIdlU32";
  } else if (isI32Type(type)) {
    return "chkIdlI32";
  } else if (isU64Type(type)) {
    return "chkIdlU64";
  } else if (isI64Type(type)) {
    return "chkIdlI64";
  } else if (isFloatType(type)) {
    return "chkIdlFloat";
  } else if (isDoubleType(type)) {
    return "TypeChk.isNumber";
  } else if (isU64Type(type)) {
    return 'chkIdlU64';
  } else if (isI64Type(type)) {
    return 'chkIdlI64';
  } else if (isStringType(type)) {
    return 'TypeChk.isString';
  } else if (isCharType(type)) {
    return 'chkIdlChar';
  } else if (isBoolType(type)) {
    return 'TypeChk.isBoolean';
  } else if (isRefType(type)) {
    return `chk${type.r}`;
  } else if (isArrayType(type)) {
    return `chkArrayOf(${getTypeName(type.d)})`;
  } else if (isSetType(type) || isFastSetType(type)) {
    return `chkSetOf(${getTypeName(type.d)})`;
  } else if (isMapType(type) || isFastMapType(type)) {
    return `chkMapOf(${getTypeName(type.k)}, ${getTypeName(type.v)})`;
  } else if (isTupleType(type)) {
    return `[${type.l.map(getTypeName).join(', ')}]`;
  } else if (isObjectType(type) || isSubType(type)) {
    return 'chkObjectOfType(...)';
  } else if (isEnumType(type)) {
    return `chkEnumType(${type.})`;
  }
  throw new Error(`Unsupported unnamed type: ${JSON.stringify(type)}`);
}
const enumType: EmitItem<Enum> = async (writer, name, item) => {
  await writer.write(`
export const ${name} = Object.freeze({
  ${item.v.map((val, idx) => `${val}: ${idx}`).join(',\n  ')}
});
export type ${name} = (typeof ${name})[keyof typeof ${name}];
export const is${name}: TypeChk.typecheck<${name}> = (val: unknown): val is ${name} => {
  return TypeChk.isString(val) && Object.values(${name}).includes(val as ${name});
};
`);
};

const numEnumType: EmitItem<NEnum> = async (writer, name, item) => {
  await writer.write(`
export const ${name} = Object.freeze({
${Object.entries(item.v)
      .map(([key, value]) => `  ${key}: ${value},`)
      .join('\n')}
});
export type ${name} = (typeof ${name})[keyof typeof ${name}];
export const is${name}: TypeChk.typecheck<${name}> = (val: unknown): val is ${name} => {
  return TypeChk.isNumber(val) && Object.values(${name}).includes(val as ${name});
}
`);
};

const strEnumType: EmitItem<SEnum> = async (writer, name, item) => {
  await writer.write(`
export const ${name} = Object.freeze({
${Object.entries(item.v)
      .map(([key, val]) => `  ${key}: '${SingleQuoteSafe(val)}',`)
      .join('\n')}
});
export type ${name} = (typeof ${name})[keyof typeof ${name}];
export const is${name}: TypeChk.typecheck<${name}> = (val: unknown): val is ${name} => {
  return TypeChk.isString(val) && Object.values(${name}).includes(val as ${name});
};
`);
};

const objType: EmitItem<ObjType> = async (writer, name, item) => {
  await writer.write(`
export type ${name} = {`);
  for (const [key, value] of Object.entries(item.d)) {
    const typeName = getTypeName(value);
    await writer.write(`\n  ${key}: ${typeName};`);
  }
  await writer.write(`
}
export const is${name}: TypeChk.typecheck<${name}> = (val: unknown): val is ${name} => {
    return TypeChk.isObjectOfType(val, {
    ${Object.entries(item.d).map(([key, value]) => `  ${key}: ${getTypeCheckName(value)};`).join('\n')}
    });
}`);
};

const subType: EmitItem<SubType> = async (writer, name, item) => {
  await writer.write(`
export type ${ name } = ${ item.p } & {`);
  for (const [key, value] of Object.entries(item.d)) {
    const typeName = getTypeName(value);
    await writer.write(`\n  ${ key }: ${ typeName }; `);
  }
  await writer.write('\n};\n');
};

const simpleType: EmitItem<Types> = async (writer, name, item) => {
  await writer.write(`
export type ${ name } = ${ getTypeName(item) };
`);
};

export const TypescriptEmitter: Emitter = {
  header,
  footer,
  types: {
    objType,
    subType,
    arrType: simpleType,
    setType: simpleType,
    fastSetType: simpleType,
    mapType: simpleType,
    fastMapType: simpleType,
    tupType: simpleType,
    enumType,
    strType: simpleType,
    numEnumType,
    strEnumType,
  },
};

export function GetTypescriptGenerator(): FileGenerator {
  // Returns the TypescriptEmitter instance
  return MakeGenerator(TypescriptEmitter);
}
