// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from www/Shared/Enums.ts by running 'bun gen'
// If you need to change this file, edit www/Shared/Enums.ts and run
// 'bun gen' again. Or, if you need to change the generation
// process, edit scripts/emitters/cpp.ts and run 'bun gen' again.
// DO NOT EDIT THIS FILE DIRECTLY!!!

#pragma once

#ifndef SHARED_CONSTANTS_HPP
#define SHARED_CONSTANTS_HPP

#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

namespace Shared {
template <typename T>
constexpr std::optional<T> from_string(const std::string_view& str);

// Keys
enum class Keys {
  AddFileLocation,
  Albums,
  Artists,
  Backward10s,
  Find,
  Forward10s,
  NextTrack,
  NowPlaying,
  Play,
  Playlists,
  PreviousTrack,
  Repeat,
  SavePlaylist,
  Settings,
  Shuffle,
  Songs,
  ToggleMiniPlayer,
  Tools
};

inline constexpr std::string_view to_string(Keys _value) {
  switch (_value) {
    case Keys::AddFileLocation:
      return "O";
    case Keys::Albums:
      return "2";
    case Keys::Artists:
      return "3";
    case Keys::Backward10s:
      return "[";
    case Keys::Find:
      return "F";
    case Keys::Forward10s:
      return "]";
    case Keys::NextTrack:
      return "Right";
    case Keys::NowPlaying:
      return "1";
    case Keys::Play:
      return "P";
    case Keys::Playlists:
      return "5";
    case Keys::PreviousTrack:
      return "Left";
    case Keys::Repeat:
      return "T";
    case Keys::SavePlaylist:
      return "S";
    case Keys::Settings:
      return ",";
    case Keys::Shuffle:
      return "R";
    case Keys::Songs:
      return "4";
    case Keys::ToggleMiniPlayer:
      return "9";
    case Keys::Tools:
      return "L";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<Keys> from_string<Keys>(
    const std::string_view& str) {
  if (str == "O")
    return Keys::AddFileLocation;
  if (str == "2")
    return Keys::Albums;
  if (str == "3")
    return Keys::Artists;
  if (str == "[")
    return Keys::Backward10s;
  if (str == "F")
    return Keys::Find;
  if (str == "]")
    return Keys::Forward10s;
  if (str == "Right")
    return Keys::NextTrack;
  if (str == "1")
    return Keys::NowPlaying;
  if (str == "P")
    return Keys::Play;
  if (str == "5")
    return Keys::Playlists;
  if (str == "Left")
    return Keys::PreviousTrack;
  if (str == "T")
    return Keys::Repeat;
  if (str == "S")
    return Keys::SavePlaylist;
  if (str == ",")
    return Keys::Settings;
  if (str == "R")
    return Keys::Shuffle;
  if (str == "4")
    return Keys::Songs;
  if (str == "9")
    return Keys::ToggleMiniPlayer;
  if (str == "L")
    return Keys::Tools;
  return std::nullopt;
}

// StrId
enum class StrId {
  Mono,
  Stereo,
  Quadrophonic,
  Channels,
  BitDepth,
  FilePath,
  Duration,
  MDHeaderField,
  MDHeaderValue,
  FilesSelected,
  RawMetadata,
  ChooseCoverArt,
  ImageName,
  ErrNotSingleAndNotMultiple,
  ErrSingleAndMultiple,
  Title,
  ArtistTooltip,
  Artists,
  Album,
  Year,
  TrackNum,
  DiskNum,
  DiskName,
  Compilation,
  Soundtrack,
  AdditionalArtists,
  VariationsTooltip,
  Variations,
  AlbumCover,
  ChooseFile,
  FromClipboard,
  ViewNowPlaying,
  ViewAlbums,
  ViewArtists,
  ViewSongs,
  ViewPlaylists,
  ViewSettings,
  ViewTools,
  ImportFiles
};

inline constexpr std::string_view to_string(StrId _value) {
  switch (_value) {
    case StrId::Mono:
      return "mono";
    case StrId::Stereo:
      return "stereo";
    case StrId::Quadrophonic:
      return "quadrophonic";
    case StrId::Channels:
      return " channels";
    case StrId::BitDepth:
      return "bit";
    case StrId::FilePath:
      return "File Path";
    case StrId::Duration:
      return "Duration:";
    case StrId::MDHeaderField:
      return "Field";
    case StrId::MDHeaderValue:
      return "Value";
    case StrId::FilesSelected:
      return "Files Selected";
    case StrId::RawMetadata:
      return "Raw Metadata";
    case StrId::ChooseCoverArt:
      return "Select Cover Art Image";
    case StrId::ImageName:
      return "Images";
    case StrId::ErrNotSingleAndNotMultiple:
      return "Not Single and not Multiple (This is a bug!)";
    case StrId::ErrSingleAndMultiple:
      return "Both Single and Multiple (This is a bug!)";
    case StrId::Title:
      return "Title";
    case StrId::ArtistTooltip:
      return "Multiple artists are specified like this: 'Artist 1, Artist 2 & "
             "Artist 3'";
    case StrId::Artists:
      return "Artist(s)";
    case StrId::Album:
      return "Album";
    case StrId::Year:
      return "Year";
    case StrId::TrackNum:
      return "Track #";
    case StrId::DiskNum:
      return "Disk #";
    case StrId::DiskName:
      return "Disk Name";
    case StrId::Compilation:
      return "Compilation";
    case StrId::Soundtrack:
      return "Soundtrack";
    case StrId::AdditionalArtists:
      return "Additional Artist(s)";
    case StrId::VariationsTooltip:
      return "Separate vartiations with a semicolon";
    case StrId::Variations:
      return "Variation(s)";
    case StrId::AlbumCover:
      return "Album Cover";
    case StrId::ChooseFile:
      return "Choose File...";
    case StrId::FromClipboard:
      return "From Clipboard";
    case StrId::ViewNowPlaying:
      return "Now Playing";
    case StrId::ViewAlbums:
      return "Albums";
    case StrId::ViewArtists:
      return "Artists";
    case StrId::ViewSongs:
      return "All Songs";
    case StrId::ViewPlaylists:
      return "Playlists";
    case StrId::ViewSettings:
      return "Settings";
    case StrId::ViewTools:
      return "Tools";
    case StrId::ImportFiles:
      return "Import Files...";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<StrId> from_string<StrId>(
    const std::string_view& str) {
  if (str == "mono")
    return StrId::Mono;
  if (str == "stereo")
    return StrId::Stereo;
  if (str == "quadrophonic")
    return StrId::Quadrophonic;
  if (str == " channels")
    return StrId::Channels;
  if (str == "bit")
    return StrId::BitDepth;
  if (str == "File Path")
    return StrId::FilePath;
  if (str == "Duration:")
    return StrId::Duration;
  if (str == "Field")
    return StrId::MDHeaderField;
  if (str == "Value")
    return StrId::MDHeaderValue;
  if (str == "Files Selected")
    return StrId::FilesSelected;
  if (str == "Raw Metadata")
    return StrId::RawMetadata;
  if (str == "Select Cover Art Image")
    return StrId::ChooseCoverArt;
  if (str == "Images")
    return StrId::ImageName;
  if (str == "Not Single and not Multiple (This is a bug!)")
    return StrId::ErrNotSingleAndNotMultiple;
  if (str == "Both Single and Multiple (This is a bug!)")
    return StrId::ErrSingleAndMultiple;
  if (str == "Title")
    return StrId::Title;
  if (str ==
      "Multiple artists are specified like this: 'Artist 1, Artist 2 & Artist "
      "3'")
    return StrId::ArtistTooltip;
  if (str == "Artist(s)")
    return StrId::Artists;
  if (str == "Album")
    return StrId::Album;
  if (str == "Year")
    return StrId::Year;
  if (str == "Track #")
    return StrId::TrackNum;
  if (str == "Disk #")
    return StrId::DiskNum;
  if (str == "Disk Name")
    return StrId::DiskName;
  if (str == "Compilation")
    return StrId::Compilation;
  if (str == "Soundtrack")
    return StrId::Soundtrack;
  if (str == "Additional Artist(s)")
    return StrId::AdditionalArtists;
  if (str == "Separate vartiations with a semicolon")
    return StrId::VariationsTooltip;
  if (str == "Variation(s)")
    return StrId::Variations;
  if (str == "Album Cover")
    return StrId::AlbumCover;
  if (str == "Choose File...")
    return StrId::ChooseFile;
  if (str == "From Clipboard")
    return StrId::FromClipboard;
  if (str == "Now Playing")
    return StrId::ViewNowPlaying;
  if (str == "Albums")
    return StrId::ViewAlbums;
  if (str == "Artists")
    return StrId::ViewArtists;
  if (str == "All Songs")
    return StrId::ViewSongs;
  if (str == "Playlists")
    return StrId::ViewPlaylists;
  if (str == "Settings")
    return StrId::ViewSettings;
  if (str == "Tools")
    return StrId::ViewTools;
  if (str == "Import Files...")
    return StrId::ImportFiles;
  return std::nullopt;
}

enum class CurrentView {
  disabled = -1,
  none = 0,
  recent = 1,
  albums = 2,
  artists = 3,
  songs = 4,
  playlists = 5,
  now_playing = 6,
  settings = 7,
  search = 8,
  tools = 9,
};
// IpcId
enum class IpcId {
  ClearHates,
  ClearLikes,
  ClearLocalOverrides,
  DeletePlaylist,
  FlushImageCache,
  FlushMetadataCache,
  GetHates,
  GetLikes,
  GetMediaInfo,
  GetMusicDatabase,
  GetPlaylists,
  LoadPlaylist,
  ManualRescan,
  MenuAction,
  MusicDBUpdate,
  RenamePlaylist,
  SavePlaylist,
  Search,
  SetHates,
  SetLikes,
  SetMediaInfo,
  SetPlaylists,
  SetSaveMenu,
  ShowFile,
  ShowLocFromKey,
  ShowMenu,
  SubstrSearch,
  TranscodingUpdate,
  TranscodingBegin,
  UploadImage,
  MinimizeWindow,
  MaximizeWindow,
  RestoreWindow,
  CloseWindow,
  GetPicUri,
  GetIgnoreList,
  AddIgnoreItem,
  RemoveIgnoreItem,
  PushIgnoreList,
  IgnoreListId,
  RescanInProgress
};

inline constexpr std::string_view to_string(IpcId _value) {
  switch (_value) {
    case IpcId::ClearHates:
      return "clear-hates";
    case IpcId::ClearLikes:
      return "clear-likes";
    case IpcId::ClearLocalOverrides:
      return "clear-local-overrides";
    case IpcId::DeletePlaylist:
      return "delete-playlist";
    case IpcId::FlushImageCache:
      return "flush-image-cache";
    case IpcId::FlushMetadataCache:
      return "flush-metadata-cache";
    case IpcId::GetHates:
      return "get-hates";
    case IpcId::GetLikes:
      return "get-likes";
    case IpcId::GetMediaInfo:
      return "media-info";
    case IpcId::GetMusicDatabase:
      return "get-music-database";
    case IpcId::GetPlaylists:
      return "get-playlists";
    case IpcId::LoadPlaylist:
      return "load-playlist";
    case IpcId::ManualRescan:
      return "manual-rescan";
    case IpcId::MenuAction:
      return "menuAction";
    case IpcId::MusicDBUpdate:
      return "music-database-update";
    case IpcId::RenamePlaylist:
      return "rename-playlist";
    case IpcId::SavePlaylist:
      return "save-playlist";
    case IpcId::Search:
      return "search";
    case IpcId::SetHates:
      return "set-hates";
    case IpcId::SetLikes:
      return "set-likes";
    case IpcId::SetMediaInfo:
      return "set-media-info";
    case IpcId::SetPlaylists:
      return "set-playlists";
    case IpcId::SetSaveMenu:
      return "set-save-menu";
    case IpcId::ShowFile:
      return "show-file";
    case IpcId::ShowLocFromKey:
      return "show-location-from-key";
    case IpcId::ShowMenu:
      return "show-menu";
    case IpcId::SubstrSearch:
      return "subsearch";
    case IpcId::TranscodingUpdate:
      return "get-xcode-update";
    case IpcId::TranscodingBegin:
      return "start-xcode";
    case IpcId::UploadImage:
      return "upload-image";
    case IpcId::MinimizeWindow:
      return "minimize-window";
    case IpcId::MaximizeWindow:
      return "maximize-window";
    case IpcId::RestoreWindow:
      return "restore-window";
    case IpcId::CloseWindow:
      return "close-window";
    case IpcId::GetPicUri:
      return "get-pic-uri";
    case IpcId::GetIgnoreList:
      return "get-ignore-list";
    case IpcId::AddIgnoreItem:
      return "add-ignore-item";
    case IpcId::RemoveIgnoreItem:
      return "del-ignore-item";
    case IpcId::PushIgnoreList:
      return "push-ignore-list";
    case IpcId::IgnoreListId:
      return "ignore-list";
    case IpcId::RescanInProgress:
      return "rescan-in-progress";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<IpcId> from_string<IpcId>(
    const std::string_view& str) {
  if (str == "clear-hates")
    return IpcId::ClearHates;
  if (str == "clear-likes")
    return IpcId::ClearLikes;
  if (str == "clear-local-overrides")
    return IpcId::ClearLocalOverrides;
  if (str == "delete-playlist")
    return IpcId::DeletePlaylist;
  if (str == "flush-image-cache")
    return IpcId::FlushImageCache;
  if (str == "flush-metadata-cache")
    return IpcId::FlushMetadataCache;
  if (str == "get-hates")
    return IpcId::GetHates;
  if (str == "get-likes")
    return IpcId::GetLikes;
  if (str == "media-info")
    return IpcId::GetMediaInfo;
  if (str == "get-music-database")
    return IpcId::GetMusicDatabase;
  if (str == "get-playlists")
    return IpcId::GetPlaylists;
  if (str == "load-playlist")
    return IpcId::LoadPlaylist;
  if (str == "manual-rescan")
    return IpcId::ManualRescan;
  if (str == "menuAction")
    return IpcId::MenuAction;
  if (str == "music-database-update")
    return IpcId::MusicDBUpdate;
  if (str == "rename-playlist")
    return IpcId::RenamePlaylist;
  if (str == "save-playlist")
    return IpcId::SavePlaylist;
  if (str == "search")
    return IpcId::Search;
  if (str == "set-hates")
    return IpcId::SetHates;
  if (str == "set-likes")
    return IpcId::SetLikes;
  if (str == "set-media-info")
    return IpcId::SetMediaInfo;
  if (str == "set-playlists")
    return IpcId::SetPlaylists;
  if (str == "set-save-menu")
    return IpcId::SetSaveMenu;
  if (str == "show-file")
    return IpcId::ShowFile;
  if (str == "show-location-from-key")
    return IpcId::ShowLocFromKey;
  if (str == "show-menu")
    return IpcId::ShowMenu;
  if (str == "subsearch")
    return IpcId::SubstrSearch;
  if (str == "get-xcode-update")
    return IpcId::TranscodingUpdate;
  if (str == "start-xcode")
    return IpcId::TranscodingBegin;
  if (str == "upload-image")
    return IpcId::UploadImage;
  if (str == "minimize-window")
    return IpcId::MinimizeWindow;
  if (str == "maximize-window")
    return IpcId::MaximizeWindow;
  if (str == "restore-window")
    return IpcId::RestoreWindow;
  if (str == "close-window")
    return IpcId::CloseWindow;
  if (str == "get-pic-uri")
    return IpcId::GetPicUri;
  if (str == "get-ignore-list")
    return IpcId::GetIgnoreList;
  if (str == "add-ignore-item")
    return IpcId::AddIgnoreItem;
  if (str == "del-ignore-item")
    return IpcId::RemoveIgnoreItem;
  if (str == "push-ignore-list")
    return IpcId::PushIgnoreList;
  if (str == "ignore-list")
    return IpcId::IgnoreListId;
  if (str == "rescan-in-progress")
    return IpcId::RescanInProgress;
  return std::nullopt;
}

// IgnoreItemType
enum class IgnoreItemType { PathRoot, PathKeyword, DirName };

inline constexpr std::string_view to_string(IgnoreItemType _value) {
  switch (_value) {
    case IgnoreItemType::PathRoot:
      return "path-root";
    case IgnoreItemType::PathKeyword:
      return "path-keyword";
    case IgnoreItemType::DirName:
      return "dir-name";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<IgnoreItemType> from_string<IgnoreItemType>(
    const std::string_view& str) {
  if (str == "path-root")
    return IgnoreItemType::PathRoot;
  if (str == "path-keyword")
    return IgnoreItemType::PathKeyword;
  if (str == "dir-name")
    return IgnoreItemType::DirName;
  return std::nullopt;
}

// StorageId
enum class StorageId {
  CurrentView,
  CurrentIndex,
  PlaybackOrder,
  NowPlaying,
  CurrentSongList,
  Shuffle,
  Repeat,
  NeverPlayHates,
  OnlyPlayLikes,
  FullAlbumsOnly,
  MinSongCount,
  Mute,
  LikedSongs,
  HatedSongs,
  Volume,
  Locations,
  DefaultLocation,
  SortWithArticles,
  DownloadAlbumArtwork,
  DownloadArtistArtwork,
  SaveAlbumArtworkWithMusic,
  AlbumCoverName,
  TranscodingUpdate,
  TranscodeSrcLocDir,
  TranscodeSrcLocPlaylist,
  TranscodeSrcLocArtist,
  TranscodeSrcLocAlbum,
  TranscodeDestLoc,
  TranscodeBitRate
};

inline constexpr std::string_view to_string(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
      return "CurrentView";
    case StorageId::CurrentIndex:
      return "currentIndex";
    case StorageId::PlaybackOrder:
      return "playbackOrder";
    case StorageId::NowPlaying:
      return "nowPlaying";
    case StorageId::CurrentSongList:
      return "currentSongList";
    case StorageId::Shuffle:
      return "shuffle";
    case StorageId::Repeat:
      return "repeat";
    case StorageId::NeverPlayHates:
      return "neverPlayHates";
    case StorageId::OnlyPlayLikes:
      return "onlyPlayLikes";
    case StorageId::FullAlbumsOnly:
      return "FullAlbumsOnly";
    case StorageId::MinSongCount:
      return "MinSongCount";
    case StorageId::Mute:
      return "mute";
    case StorageId::LikedSongs:
      return "likedSongs";
    case StorageId::HatedSongs:
      return "hatedSongs";
    case StorageId::Volume:
      return "volume";
    case StorageId::Locations:
      return "locations";
    case StorageId::DefaultLocation:
      return "defaultLocation";
    case StorageId::SortWithArticles:
      return "rSortWithArticles";
    case StorageId::DownloadAlbumArtwork:
      return "downloadAlbumArtwork";
    case StorageId::DownloadArtistArtwork:
      return "downloadArtistArtwork";
    case StorageId::SaveAlbumArtworkWithMusic:
      return "saveAlbumArtworkWithMusic";
    case StorageId::AlbumCoverName:
      return "albumCoverName";
    case StorageId::TranscodingUpdate:
      return "get-xcode-update";
    case StorageId::TranscodeSrcLocDir:
      return "xcodeSrcLocDir";
    case StorageId::TranscodeSrcLocPlaylist:
      return "xcodeSrcLocPlaylist";
    case StorageId::TranscodeSrcLocArtist:
      return "xcodeSrcLocArtist";
    case StorageId::TranscodeSrcLocAlbum:
      return "xcodeSrcLocAlbum";
    case StorageId::TranscodeDestLoc:
      return "xcodeDestLoc";
    case StorageId::TranscodeBitRate:
      return "xcodeBitRate";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<StorageId> from_string<StorageId>(
    const std::string_view& str) {
  if (str == "CurrentView")
    return StorageId::CurrentView;
  if (str == "currentIndex")
    return StorageId::CurrentIndex;
  if (str == "playbackOrder")
    return StorageId::PlaybackOrder;
  if (str == "nowPlaying")
    return StorageId::NowPlaying;
  if (str == "currentSongList")
    return StorageId::CurrentSongList;
  if (str == "shuffle")
    return StorageId::Shuffle;
  if (str == "repeat")
    return StorageId::Repeat;
  if (str == "neverPlayHates")
    return StorageId::NeverPlayHates;
  if (str == "onlyPlayLikes")
    return StorageId::OnlyPlayLikes;
  if (str == "FullAlbumsOnly")
    return StorageId::FullAlbumsOnly;
  if (str == "MinSongCount")
    return StorageId::MinSongCount;
  if (str == "mute")
    return StorageId::Mute;
  if (str == "likedSongs")
    return StorageId::LikedSongs;
  if (str == "hatedSongs")
    return StorageId::HatedSongs;
  if (str == "volume")
    return StorageId::Volume;
  if (str == "locations")
    return StorageId::Locations;
  if (str == "defaultLocation")
    return StorageId::DefaultLocation;
  if (str == "rSortWithArticles")
    return StorageId::SortWithArticles;
  if (str == "downloadAlbumArtwork")
    return StorageId::DownloadAlbumArtwork;
  if (str == "downloadArtistArtwork")
    return StorageId::DownloadArtistArtwork;
  if (str == "saveAlbumArtworkWithMusic")
    return StorageId::SaveAlbumArtworkWithMusic;
  if (str == "albumCoverName")
    return StorageId::AlbumCoverName;
  if (str == "get-xcode-update")
    return StorageId::TranscodingUpdate;
  if (str == "xcodeSrcLocDir")
    return StorageId::TranscodeSrcLocDir;
  if (str == "xcodeSrcLocPlaylist")
    return StorageId::TranscodeSrcLocPlaylist;
  if (str == "xcodeSrcLocArtist")
    return StorageId::TranscodeSrcLocArtist;
  if (str == "xcodeSrcLocAlbum")
    return StorageId::TranscodeSrcLocAlbum;
  if (str == "xcodeDestLoc")
    return StorageId::TranscodeDestLoc;
  if (str == "xcodeBitRate")
    return StorageId::TranscodeBitRate;
  return std::nullopt;
}

// TranscodeFormatTargetName
enum class TranscodeFormatTargetName { m4a, mp3, aac };

inline constexpr std::string_view to_string(TranscodeFormatTargetName _value) {
  switch (_value) {
    case TranscodeFormatTargetName::m4a:
      return "m4a";
    case TranscodeFormatTargetName::mp3:
      return "mp3";
    case TranscodeFormatTargetName::aac:
      return "aac";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<TranscodeFormatTargetName>
from_string<TranscodeFormatTargetName>(const std::string_view& str) {
  if (str == "m4a")
    return TranscodeFormatTargetName::m4a;
  if (str == "mp3")
    return TranscodeFormatTargetName::mp3;
  if (str == "aac")
    return TranscodeFormatTargetName::aac;
  return std::nullopt;
}

// TranscodeSource
enum class TranscodeSource { Playlist, Artist, Album, Disk };

inline constexpr std::string_view to_string(TranscodeSource _value) {
  switch (_value) {
    case TranscodeSource::Playlist:
      return "p";
    case TranscodeSource::Artist:
      return "r";
    case TranscodeSource::Album:
      return "l";
    case TranscodeSource::Disk:
      return "d";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<TranscodeSource> from_string<TranscodeSource>(
    const std::string_view& str) {
  if (str == "p")
    return TranscodeSource::Playlist;
  if (str == "r")
    return TranscodeSource::Artist;
  if (str == "l")
    return TranscodeSource::Album;
  if (str == "d")
    return TranscodeSource::Disk;
  return std::nullopt;
}
struct TranscodeSourceLocation {
  TranscodeSource type;
  std::string loc;
};

struct FileFailure {
  std::string file;
  std::string error;
};

struct TranscodeState {
  std::string curStatus;
  std::vector<std::string> filesTranscoded;
  std::int32_t filesFound;
  std::int32_t filesPending;
  std::int32_t filesUntouched;
  std::vector<FileFailure> filesFailed;
  std::vector<std::string> itemsRemoved;
};

struct TranscodeInfo {
  TranscodeSourceLocation source;
  std::string dest;
  bool artwork;
  bool mirror;
  TranscodeFormatTargetName format;
  std::uint16_t bitrate;
};
